### ISSUE TITLE
Add type of number on last call list

### ISSUE THREAD

**Issue by Vucumpra** [FossifyOrg/Phone#106]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Hello,

Can you add a number type on each call for last call list ?

Example : 

For my professional contact, I use to create a new item, not for a person but fo a company :

Name : Global Company INC
Phone 1 "Jack" : 00123644
Phone 2 "Repair" : 4596987
Phone 3 "Sale" : 0123456
...

When the sale service call me, I want to see : 
Global Company INC, **_[Sale]_**
06.03,                          00:12

So:
The name of phone number, **_[work or home or personalised type number]_**
Date,                          Conversation Time

Actually, the italic bold information is not displayed

### Why do you want this feature?

Because when a company call me, I never see who call me from this company.

**Comment by Aga-C** [comment]
I've tested it once again, and I can see that information in call log:
![image](https://github.com/FossifyOrg/Phone/assets/85929121/e92cea2e-82b6-4dfc-af40-e598b6eb506a)

While calling, I also can see the labels, even custom ones:
![image](https://github.com/FossifyOrg/Phone/assets/85929121/e8b66f1f-cf14-4400-a0f3-b57bd535c6c2)

I have this behavior both on Android 13 and 14.

@Vucumpra do you still have this problem? If yes, please answer these questions:
- Which Android version are you using?
- What contacts app are you using? And where do you store contacts?

>  or in the Contact tab.

In Contacts tab, it's obvious that it's not visible because it's just a list of contacts. A list of numbers with their types is visible after opening the contact.

**Comment by franco27** [comment]
Thank you for your response. There was confusion on my part. 
These features are indeed present. Sorry. 🙄

**Comment by franco27** [comment]
In the new version, 111, this functionality has disappeared.
I no longer have any labels.

**Comment by Aga-C** [comment]
@franco27 Please create a bug report for this.

**Comment by naveensingh** [comment]
It still works for me in version 1.1.1 but the label only appears when the dialed number exactly matches the one saved in the contacts. It doesn't work if I omit the country code.

**Comment by Vucumpra** [comment]
Ok, Thank for implemented this feature :)

But now I see a new problem : 
In the list of las t call, the first line is too short for "caller" +  "label"
A best way will be :

**Comment by volker001** [comment]
For me it doesn't work.
My phone number formatting are international.
+11 (1234) 56789
I don't see the type of number.
Neither in the call list nor when I tap call back, not even when I display the call details.
The app is great, but I can't use it like this.
Android 13 / LOS-Based.

**Comment by Vucumpra** [comment]
> For me it doesn't work. My phone number formatting are international. +11 (1234) 56789 I don't see the type of number. Neither in the call list nor when I tap call back, not even when I display the call details. The app is great, but I can't use it like this. Android 13 / LOS-Based.

Maybe is this : If you have only one number per contact, the type of number don't appear
