### ISSUE TITLE
Screen doesn't turn on

### ISSUE THREAD

**Issue by nxjosephofficial** [FossifyOrg/Phone#108]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [ ] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 14 / HyperOS by xiaomi.eu 1.0.2.0.UMTMIXM Stable

### Affected device model

Redmi Note 12 4G

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Get called by someone
2. Hearing incoming call but screen doesn't turn on

### Expected behavior

It should make screen turn on.

### Actual behavior

I hear the incoming call but screen doesn't turn on.

### Additional information

My device is rooted with magisk. My issue is written on FAQ page of the Phone app. I did the suggestions but still my screen doesn't turn on.

Phone app is allowed to pop up when in background and allowed displaying over other apps.

**Comment by Aga-C** [comment]
If anybody else also encounters this bug, please write your device model and OS version. It seems to be device/software specific, so we'd like to have as much info as possible.

**Comment by Aga-C** [comment]
Good to see that you were able to solve the problem, so I'm closing this issue.

**Comment by inson1** [comment]
@Aga-C Shouldnt we add this to the faq to this string? https://github.com/FossifyOrg/Phone/blob/c892f765222b129311bc86670a9ff79e9ad276f8/app/src/main/res/values/strings.xml#L85

**Comment by qumuq-til** [comment]
Didn't work for me. In fact, that was the first place I looked, and there's just a single option that says "Unrestricted". Still not waking the screen up, and even on a live screen it may not pop up the dialer.

**Comment by qumuq-til** [comment]
Additionally today the dialer interface woke up the phone but the screen was frozen, there was no animation and I couldn't slide the phone icon left or right to accept or deny the call. Second call after that worked normally.

**Comment by qumuq-til** [comment]
I can reliably reproduce the issue with the Phone. All you need to do is "Force stop" the app. It won't come up again on incoming calls and the phone will still ring.
Google's Phone app doesn't care about being force stopped even with Google Services disabled and will always come up on an incoming call.

**Comment by Aga-C** [comment]
@qumuq-til Please create the new bug report that describes precisely the issue you're facing.

**Comment by NickAndreou** [comment]
I had this a number of times, before going on vacation some time ago. Android 15/HyperOS 2.203/Xiaomi 12 
Will apply no restrictions on battery, let's see.
