### ISSUE TITLE
Force stopping Phone in the Apps panel disables handling of incoming calls

### ISSUE THREAD

**Issue by qumuq-til** [FossifyOrg/Phone#111]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 13

### Affected device model

Ulefone Armor 18T Ultra

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Run "Phone" (Fossify) and set it as default
2. Go to Settings/Apps page
3. Search for "Phone" (Google) and enter the app properties page
4. Tap "Disable" and confirm you want to disable the app
5. Tap "Force stop" and confirm you want to stop the app
7. Search for "Phone" (Fossify) and enter the app properties page
8. Tap "Force stop" and confirm you want to stop the app
9. Make an incoming call to your device, it doesn't matter if the screen is off or not
10. Observe that there's a ring but no Phone app interface 

### Expected behavior

Phone app should get (re)started whenever there's an incoming call, regardless of whether it was manually stopped or stopped by some app-killing service in the device's OS.

### Actual behavior

Phone app doesn't get started if it was stopped.

### Additional information

If you don't disable Phone (Google) on step 4, it will handle the call instead when Phone (Fossify) can't start up, even if it's not set as default.

**Comment by Aga-C** [comment]
If anybody else also encounters this bug, please write your device model and OS version. It seems to be device/software specific, so we'd like to have as much info as possible.

**Comment by Aga-C** [comment]
@qumuq-til Have you disabled/uninstalled any system services related to telephony? And are they reverted after receiving a call if you don't disable Google Phone in step 4?

**Comment by qumuq-til** [comment]
@Aga-C I've had many packages disabled, and just a cursory look suggests that nothing gets re-enabled after receiving a call via Google Phone, however I've made an even simpler test: I've re-enabled all the packages so none were uninstalled or disabled on the device, and followed the same steps I described in the report. I'm still getting the same behaviour: Phone wouldn't start up.

The only package that got disabled somehow along the line was "com.mediatek.todos" but I cannot find a way to re-enable it, just errors out.

Disabling Google Phone using Settings seems to have also disabled "com.google.android.gms.supervision" and I cannot re-enable it again whatsoever, even after rebooting. That package was enabled before and I'm not sure what made it disabled now and why it cannot be re-enabled.

**Comment by qumuq-til** [comment]
Regardless of the models and OS versions we have to devise a way to see into what's happening exactly and why Phone cannot respond with an app start after an incoming call is detected.

**Comment by chesio** [comment]
> Regardless of the models and OS versions we have to devise a way to see into what's happening exactly and why Phone cannot respond with an app start after an incoming call is detected.

It seems to be device / ROM specific. I've tried to reproduce the problem, but failed. I already have Google Phone app disabled and Fossify Phone as default phone app, so I just force-stopped it, but I still get a system notification and can answer the phone. I am on Android 13 as well.

**Comment by qumuq-til** [comment]
I've found the culprit. It's "com.mediatek.duraspeed". It's a system app that takes over Android's own battery management and uses its own algorithm. I have uninstalled that app some time ago thinking it would stop it from interfering and indeed its entry in Settings was gone. But it was still active in the system despite that. After I re-installed it back I browsed its activity pane and it was aggressively freezing apps, including Phone. Google Phone mysteriously circumvented Duraspeed even though it wasn't in the exclusion list. Finally I simply turned Duraspeed off using its own interface and the problem was gone.

So it may be a bit of a crutch, but I think checking for the presence of Duraspeed should be integrated into Phone, not least because Phone is such an essential application that must always be available to take and place calls.

Some more info here: https://github.com/urbandroid-team/dont-kill-my-app/issues/57
It's important to note people found that just querying for whether or not Duraspeed is enabled may not give correct results in every case, and there's a separate service called "ActivityManager" that actually handles all those freezes.

Looking for Duraspeed API brings this:
https://gitlab.com/SahilSonar/mediatek-alps/-/tree/master/duraspeed
It's completely conceivable that API may be used by Phone to add an exception, which would be the best solution.

Since I own the device with Duraspeed, I'm available for further testing if need be.

**Comment by naveensingh** [comment]
Thanks for filing the issue but there are way too many devices out there with aggressive battery optimizers so it'll just be a mess if we try to handle all that. Smartphone vendors with aggressive battery optimization usually provide users a way to add important apps to whitelist either using the recent apps screen or the system UI or at least they don't kill the apps that have "Battery usage" set to "Unrestricted".

Also, force stop is called "Force stop" for a reason. The user is not expected to force stop such an essential application and in case the user does force stop it for any reason, the user should then start the app manually.

**Comment by Giantvince1** [comment]
This issue has been reproducing itself on my Google Pixel 7 Pro running LineageOS 21, with the latest versions of the application, the OS of choice, and the vendor framework all installed. I have disabled any and all measures of battery optimizations in the OS itself, and the app is set as the default phone app. However, despite all this, it still refuses to actually properly handle incoming calls. I have it set to display a full-screen notification no matter what I'm doing any time a call comes in as that's how I WANT a phone to behave, but it rarely listens to this setting anymore and refuses to bring up the UI when I do manage to answer the call another way.

**Comment by naveensingh** [comment]
@Giantvince1 do you still see the call notification or is it just ringing in the background?

**Comment by Giantvince1** [comment]
It just rings in the background when the issue occurs, and it'll even happen without having force stopped the app in several days. Sometimes the notification will appear as a banner but it'll be completely unresponsive, only being able to answer using the Google Assistant to actually answer the call. During this, the in-call UI will refuse to show at all no matter what, eliminating numpad input for any possible IVR menus as well. It also refuses to show the "call in progress" notification if it occurs, 100% of the time.

**Comment by qumuq-til** [comment]
@Giantvince1 Does it work immediately after you wake the phone application up? Does it stop working after some time had passed? In my case it was active for some time, within an hour, after which the notification stopped appearing. Interesting how behaves in your case.

**Comment by Giantvince1** [comment]
It does work perfectly initially, but if for any reason the notification is interrupted or backed out of at all without answering, it ceases to function until I manually kill and restart the app before another call comes in, or it will endlessly loop in that unresponsive state. It even happens if 2 calls come in at the same time via different methods, such as a VoIP call coming in through Google Voice (like TextNow but no ads, and premium texts work, just requires your own Internet connection for obvious reasons) whilst my phone itself is also getting a direct call. That's when the issue first cropped up in an obvious fashion for me, though it has had its glitchy moments before that occurred for the first time.

**Comment by qumuq-til** [comment]
It sounds like a bug and not a battery-related issue that I had. So basically if you open it, close it normally, put the device aside, wait for 2 hours and try to receive a call, it works?

**Comment by Giantvince1** [comment]
I have to FORCE kill it to eliminate the bug or restart my entire device, not just swipe it out of the recent apps menu. It has to be completely evicted from RAM to exit the bugged state of refusing to properly handle an incoming call, or pulling up the in-call UI after answering it. Only then will it work properly again.

**Comment by qumuq-til** [comment]
Yes, I mean, after you've done that force restart, open and leave the device idle for 2 hours, will it show the notification on an incoming call?

**Comment by Giantvince1** [comment]
Yes, it will resume working normally indefinitely after a force stop and reopen, until something happens to cause it to bug out again, like any actions mentioned earlier; backing out of the fullscreen notification without using the provided buttons, like if you accidentally backed out via system gestures or if literally any other banner-showing notification pops up in a heads-up fashion like most social media apps will do when they receive their form of a call. I did once accidentally force-close it by a long back gesture while it was receiving a call since LineageOS allows you to customize what a long side gesture can do, and that is one of the options that I found to be useful, so it's been on for ages. However even before that first gesture mishap, it has had a few moments where it didn't want to cooperate.

**Comment by naveensingh** [comment]
@Giantvince1 thanks!

> Google Phone mysteriously circumvented Duraspeed

@qumuq-til I think many such optimizers have an internal DO-NOT-KILL list for popular apps. Even Google does this kind of thing, here's an example: https://issuetracker.google.com/issues/37119304

> This is an intended behavior to allow popular apps to keep working until we have an alternative APIs in the platform for these apps to migrate.

**Comment by Giantvince1** [comment]
The new issue is now opened, issue number is #170.

**Comment by qumuq-til** [comment]
@naveensingh Well, it's a dirty trick, but we could set the phone app package name or whatever it's called to mimic Google's phone and ride the free train, right? I know vendors do that.

**Comment by qumuq-til** [comment]
Thinking further about this issue, it may be necessary to add a warning to the main page here and inside the app description about the issue with battery optimizers. I consider phone application to be one of the most critical on a phone device, so if it doesn't work, for any reason, it may cause a lot of personal trouble for the unsuspecting user. So just a simple paragraph warning a user to do tests and/or disable battery optimizers for Phone would be fine. I can write that if need be.

**Comment by Bafanger** [comment]
I have this issue Ulefone armor 27 pro android 14
