### ISSUE TITLE
Show contacts without phone number

### ISSUE THREAD

**Issue by inson1** [FossifyOrg/Phone#115]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

title
https://github.com/SimpleMobileTools/Simple-Dialer/issues/710

### Why do you want this feature?

I want to see all contacts even if I cant call them
I dont want have 2 apps on homescreen and use both of them, because of this, its already in contacts (different naming)

**Comment by Aga-C** [comment]
It's a phone app, so there's no reason to show contacts which you can't call. We don't plan adding this feature.
