### ISSUE TITLE
Feature request: Bigger contact photo on call screen

### ISSUE THREAD

**Issue by NickAndreou** [FossifyOrg/Phone#118]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Bigger contact photo in the call screen. The photo could take half of the screen or even bigger.

### Why do you want this feature?

Now the contact photo is button sized, hardly can be seen.

**Comment by naveensingh** [comment]
I have increased the avatar size by ~60%, we can not increase it further without redesigning the whole UI. The call buttons are more important.

**Comment by xBassHeadx** [comment]
This change has caused issues for small or smaller than average phone sizes. The end call button now overlays existing buttons if the screen is small. Most users will not have this issue but to solve this for everyone, an option in settings to adjust the avatar size would work based on the percentage range you find appropriate.
