### ISSUE TITLE
Add slider setting to modify vibration scale

### ISSUE THREAD

**Issue by iByteABit256** [FossifyOrg/Phone#119]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Add a new slider in user settings to allow the user to modify how much the phone should vibrate with incoming calls.

### Why do you want this feature?

I often end up missing calls because the vibration is not loud enough, so a slider would be nice to customize it.

**Comment by Aga-C** [comment]
The system is responsible for that, not our app. Some Android's let you change vibration settings for incoming calls in sounds settings.
