### ISSUE TITLE
VoIP (sip) Calling Support

### ISSUE THREAD

**Issue by pepper3k** [FossifyOrg/Phone#121]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

VoIP calling feature, so that one could make and receive VoIP calls through a SIP account, like the original functionality that was removed from the native AOSP dialer app in Android 12.

https://www.xda-developers.com/android-12-killing-native-sip-calling/

### Why do you want this feature?

Seeing how this is probably the best FOSS dialer project and generally seems like a very privacy oriented community, I think it would make sense to integrate voip calling into the dialer app, especially because this was functionality that existed up to Android 11. I'm sure this would help the project gain traction (especially in the privacy community, which grows larger every day )on the one hand, while also help the general (normie) community integrate FOSS apps as their daily drivers.

### Additional information

i would be more than willing to dedicate my time to this feature, although i would need a bit of guidance, as i have not looked much at this code.

Also there are well maintained FOSS sip libraries that can be used. 
Linphone is a good example : https://gitlab.linphone.org/BC/public/linphone-android

**Comment by Aga-C** [comment]
App has no Internet access, and we don't plan adding it, so we won't support any VoIP.

**Comment by pepper3k** [comment]
@Aga-C thanks for your quick response. can you please explain the reasoning behind this decision?

**Comment by Aga-C** [comment]
> Internet permission is probably the most misused permission in all of history so unless the app's core functionality requires Internet permission, we won't add it. That means all of the existing apps will never get access to the internet.

https://github.com/orgs/FossifyOrg/discussions/68#discussioncomment-8001994

**Comment by pepper3k** [comment]
thanks, sounds like right now it's not happening, but in the future, depending on the situation, it could be a possibility?
am i right?

also, for the foreseeable future, where would you suggest i focus my effort?

**Comment by 1-eric** [comment]
For those who need the VoIP functionality, use [Simple Dialer version 5.11.3](https://github.com/SimpleMobileTools/Simple-Dialer/releases/tag/5.11.3). The last version of Simple Dialer that supports this functionality. Simple Dialer is the predecessor of Phone.

**Comment by pepper3k** [comment]
> For those who need the VoIP functionality, use [Simple Dialer version 5.11.3](https://github.com/SimpleMobileTools/Simple-Dialer/releases/tag/5.11.3). The last version of Simple Dialer that supports this functionality. Simple Dialer is the predecessor of Phone.

thanks a lot bro! i will check it out!

**Comment by 1-eric** [comment]
I forgot to add, that Simple Dialer is just a phone app that can have a call using SIP-numbers... but it can not configure the SIP numbers/accounts. So, what I did was use the native phone/dialer app of my phone to configure the SIP-accounts, then disable this app and make Simple Dialer the default phone/dialer app.

I hope that the FossifyOrg devs one day will re-implement the VoIP/SIP functionality. I need this because when I'm in a foreign country, I often need to make a call using my home phone number while connected to the internet through the hotel's WiFi or a foreign SIM card.

**Comment by 1-eric** [comment]
You are right, Fossify Phone didn't remove this functionalty. This functionality was in Simple Dialer version 5.11.3, but was removed in the next version (5.11.4).

Fossify Phone is probably the continuation of Simple Dialer version 5.18.1.

**Comment by pepper3k** [comment]
so what's the best course of action? fork Simple Dialer 5.11.3 and try to merge the missing code to get it up to date, or try to fork the current Fossify version and re-integrate the previous sip functionality that was removed?

**Comment by naveensingh** [comment]
I don't think the functionality was ever implemented. I don't see any specific change related to this between Simple Dialer 5.11.4 and 5.11.3: https://github.com/SimpleMobileTools/Simple-Dialer/compare/5.11.3...5.11.4

**Comment by 1-eric** [comment]
With Simple Dialer 5.11.3 I have to choose the SIM or SIP-number before the call is started:
![dialer](https://github.com/FossifyOrg/Phone/assets/11178557/07353dfc-b664-45d0-a0a1-c4b701839d93)
With Simple Dialer 5.11.4 and newer I can only choose between SIM 1 and SIM 2.

Even though Simple Dialer 5.11.3 can do a SIP-call, it looks like it doesn't need internet access. For example the firewall I'm using (AFWall+) has a list of apps that I can allow/block from using internet. Simple Dialer is not on this list. So it looks like some other app is doing the SIP call.

**Comment by pepper3k** [comment]
> Maybe com.android.phone (Phone Services) is the app that is doing the SIP-calls. I have Android-10 and I can do a SIP-call, but maybe this feature has been removed from com.android.phone on Android-12 and newer.

The question is this: If you run the most recent version of fossify dialer on android 11, will it support voip calling? if so the issue would be the native AOSP dialer. If not, then there must have been some functionality removed from Simple Dialer between version .3 and .4

@naveensingh said he didn't see anything that was removed so i would assume that the first case would be correct, but @1-eric said that he tried the newer version on android 10 and it didn't work, so...maybe the required system call/API was removed from AOSP and it's not just an issue of the native dialer app.

This would explain why no permissions are required, because it's accessing the SIP trunks via the OS API calls rather than accessing the internet directly.

If this is the case, it would mean that patching the AOSP project to re-enable the deprecated system API calls would solve the problem without needing to make any changes to Fossify Dialer, or the native AOSP dialer for that matter.

Your thoughts?

**Comment by 1-eric** [comment]
I think the only difference between Simple Dialer 5.11.3 and .4 is which numbers it allows me to select as the "from"-number. After this selection the call will be handled by com.android.phone.

That means that Simple Dialer never had SIP-functionality, it only had a greater selection of phone numbers in version 5.11.3. And that the SIP-functionality (and the need for internet access) is in com.android.phone.

I think that if Fossify Phone enables the selection of SIP-numbers, SIP-calls are possible again (as long as using Android before version 12).

**Comment by pepper3k** [comment]
> I think the only difference between Simple Dialer 5.11.3 and .4 is which numbers it allows me to select as the "from"-number. After this selection the call will be handled by com.android.phone.
> 
> That means that Simple Dialer never had SIP-functionality, it only had a greater selection of phone numbers in version 5.11.3. And that the SIP-functionality (and the need for internet access) is in com.android.phone.
> 
> I think that if Fossify Phone enables the selection of SIP-numbers, SIP-calls are possible again (as long as using Android before version 12).

I see, so the "proper" solution would be to "patch" the AOSP project to bring back the native dialer funcionality, while patching the latest version of Fossify Phone to be able to select SIP numbers. Then we can have all the latest software running.

I guess the first step would be to see if the change is functioning correctly on Android 11. If it works, someone can work on somehow restoring the SIP functionality to the latest android versions.

**Comment by naveensingh** [comment]
> I think the only difference between Simple Dialer 5.11.3 and .4 is which numbers it allows me to select as the "from"-number

That is correct. Thanks for investigating into this. There were some changes related to the way SIM IDs are handled. I'll investigate this further when I'm back to work on the Phone app (soon-ish).
