### ISSUE TITLE
Allow flip to shhh

### ISSUE THREAD

**Issue by lefuturiste** [FossifyOrg/Phone#124]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Add a button that allow to ignore an incoming call, the incoming call will be still ringing (from the caller side), but the call sound will mute.
Or, like the "Flip to Shhh", detect phone flip and trigger the muting of the incoming call.

### Why do you want this feature?

The "Use Flip to Shhh" allow to ignore an incoming call without giving a clue of the receiver action, it prevent the receiver of the call to deny the call which in some circonstances will indicate a clear action from the receiver (the receiver is live).

### Additional information

https://www.howtogeek.com/798418/how-to-mute-calls-by-flipping-your-android-phone/

**Comment by lefuturiste** [comment]
Duplicate of https://github.com/FossifyOrg/Phone/issues/65

**Comment by zanyshh** [comment]
Welcome feature tho

**Comment by antodc** [comment]
In my case, the power button does exactly that: mute the call sound from your side but not from the caller side. You have to disable the option "Use power button to terminate calls" in the Accessibility settings.
