### ISSUE TITLE
Add setting for the number of entries shown in call history

### ISSUE THREAD

**Issue by figvam** [FossifyOrg/Phone#125]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Hello.
I think a setting to tweak the number of entries in the call history tab would be great to have. There was even a pull request to implement that setting in 2021, not sure if it still applies: https://github.com/SimpleMobileTools/Simple-Dialer/pull/228

### Why do you want this feature?

Currently the Call History tab shows only a limited number of past calls - only "100 before grouping", according to the original developer: https://github.com/SimpleMobileTools/Simple-Dialer/issues/56
So if you have "group calls" setting enabled and there are a few frequent contacts in your call log, the call history log will be very short.

**Comment by Aga-C** [comment]
Currently, limit without grouping is 200. There should be no limit (and no option for setting it) as there is already lazy loading every 30 entries.
