### ISSUE TITLE
Hide unnecessary sources from contacts filter

### ISSUE THREAD

**Issue by NikhilSudhakaranVG** [FossifyOrg/Phone#130]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung galaxy m21

### How did you install the app?

Google Play Store

### Steps to reproduce the bug

1.Go to Contacts
2.Click Filter
3.Shows sources . But it shows sources having 0 contacts too. it's better to display sources with at least 1 contact.

### Expected behavior

Filter Shows source with at least 1 contact.

### Actual behavior

filter shows sources having 0 contacts too

**Comment by naveensingh** [comment]
I think we should keep displaying contact sources with zero contacts but I would like to know what other people think about this.

![image](https://github.com/FossifyOrg/Phone/assets/36371707/904b27fb-10a1-4b0d-be95-c789c05b86a6)

**Comment by Aga-C** [comment]
I think it's not necessary to show these empty sources because it's not a contact management app. It should be enough to filter only on what is available. 

However, if for someone it would be useful to see empty sources here, I can consider changing my mind on it.

**Comment by naveensingh** [comment]
I'm still not convinced about it so I'm closing this now, will reconsider if it is requested again.
