### ISSUE TITLE
I get error "Contects permission is required" 

### ISSUE THREAD

**Issue by hamedsbt** [FossifyOrg/Phone#132]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

LineageOS 18.1

### Affected device model

Oneplus

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

- go to the contacts tab.
- tap on a contact.

### Expected behavior

As the app has have all permissions and set as default phone app, it should show contact details and have the ability to make a call or edit contact details.

### Actual behavior

it just shows a toast message: "Contects permission is required" and don't show contact details.

**Comment by Aga-C** [comment]
> tap on a contact.

The app itself doesn't show contact details. When you tap on a contact, it should open your default contacts app to display the details. Please check what's your default contacts app in the system and give it permissions.
