### ISSUE TITLE
Always show date inside call details as an option

### ISSUE THREAD

**Issue by e075e** [FossifyOrg/Phone#133]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

1. open call history
2. go to a number that has called you today
3. three dots at the right
4. show call details

The current behaviour shows only the time and not the date in the call details, since the call is from today.

It would be nice to always show the date in call details, this could be an option in the settings.
With this I am not speaking about the call history, since having only the time in there is more useful

### Why do you want this feature?

To make a GDPR claim a proof such as a screenshot with number, date, and time is needed.

At the moment, the user will have to wait one day to make the date appears and take the screenshot

**Comment by Aga-C** [comment]
Since these are call details, it shouldn't be optional. We should always show the full date and time.

**Comment by naveensingh** [comment]
Should be fixed in the next update.
