### ISSUE TITLE
For people who I have not called before, their names are not appearing when typed on the keypad.

### ISSUE THREAD

**Issue by yusufsunetci** [FossifyOrg/Phone#135]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 11

### Affected device model

Xiaomi Note 8 Pro

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Open the keypad.
2. Type someone who was not on the last calls, but is registered in the directory.
3. There are no results.

### Expected behavior

Rehberde kayıtlı tüm kişiler tuş takımında görünmelidir.

### Actual behavior

For people who I have not called before, their names are not appearing when typed on the keypad. Neither in the call history nor in the contacts. They are not appearing even though they are registered in the contacts.

I can find the person who I haven't call for before only by searching in the contacts. It must pull on the keypad all sorts of ways. We should be able to find these calls from the last calls section without ever entering the contacts.

**Comment by Aga-C** [comment]
Are you sure, you are using Fossify Phone app? Because the behavior you're describing isn't in the app, and there's even a feature request for it: https://github.com/FossifyOrg/Phone/issues/86.

**Comment by yusufsunetci** [comment]
Yes, I'm sure. :) I'm using Fossify Phone (and using Fossify Contacts).
Meantime I am not typing phone number in keypad. I am typing name. For example: I'm typing "3-5-6-6" in keypad for typing "Elon". But for people who I have not called before, their names are not appearing when typed on the keypad.

**Comment by Aga-C** [comment]
But it's not possible because dialpad performs search only on contacts list. It doesn't consider call log at all. 
Maybe there's something else about these contacts that make them impossible to find? For now, this bug seems like something that's not likely to happen.

**Comment by yusufsunetci** [comment]
> Maybe there's something else about these contacts that make them impossible to find?

Let me examine it for a while, then. If not, I will remove it and install it again. Thanks.

There is another problem similar to this. It's about searching on the keypad. I don't know, should I write from here or should I open a separate topic?

**Comment by yusufsunetci** [comment]
I removed and installed again. Problem solved. I haven't seen any problems for a while. Thanks.
