### ISSUE TITLE
"Wake up if the screen is off" and "cover all screen if the screen is open" are not default.

### ISSUE THREAD

**Issue by yusufsunetci** [FossifyOrg/Phone#137]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

"Wake up if the screen is off" and "cover all screen if the screen is open" are not default. It's in the settings, but most people don't know about it. They are saying the program is giving errors, it's not working well and they are deleting it. It has to come by default.

Likewise, the option to define different music for people must come default.

### Why do you want this feature?

It is more convenient to use it like this.

**Comment by Aga-C** [comment]
> "Wake up if the screen is off"

Which option do you mean? There's no such thing or any similar in settings.

> "cover all screen if the screen is open"

It's up to personal preference. If it was set differently, there will be people rising bugs why it's set to the default. That's why it's in the settings, and if people don't configure the app to their liking, it's their problem.

> Likewise, the option to define personalized music must come default.

Setting custom ringtones for contacts is a responsibility of a contacts app.

**Comment by yusufsunetci** [comment]
> Which option do you mean? There's no such thing or any similar in settings.

"Always display incoming calls in full screen." Both features are opening with the same option.

> 's up to personal preference. If it was set differently, there will be people rising bugs why it's set to the default. That's why it's in the settings, and if people don't configure the app to their liking, it's their problem.

Ok. I've already arranged it. But people are get used to it. When the phone rings, it will be full screen. That's why I forwarded it to you.

> Setting custom ringtones for contacts is a responsibility of a contacts app.

Ok.

Thanks for your interest.
