### ISSUE TITLE
Sometimes, when a call comes in, the call tone is heard, but there is not warning on the screen.

### ISSUE THREAD

**Issue by yusufsunetci** [FossifyOrg/Phone#142]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 13

### Affected device model

General Mobile G23

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

A call comes in
The call tone is heard
But there is not warning on the screen.
When the call ends, a notification is comes.

### Expected behavior

When a call comes in, I should be able to open the phone.

### Actual behavior

Sometimes, when a call comes in, the call tone is heard, but there is not warning on the screen. When the call ends, a notification is comes. (This is the problem of my friend's phone.)

**Comment by Kiwigoldfish** [comment]
I'm getting similar behaviour on version 1.1.1

Android 11, Qin F21 Pro phone

If the phone rings while sleeping it regularly doesn't show anything on the screen - I have to go in and unlock the screen and open the app all while the phone rings.

I've checked all settings that I can

**Comment by Esmolante** [comment]
Same behavior described in 1.2.0 and HyperOS. The ringtone rings, but the screen remains off. If it is turned on, the call notification does not appear either. You have to go to the notification center to find it.

**Comment by dontfearSP** [comment]
I'm having the same issue. HyperOS, using v1.2.0 of Fossify Phone.

**Comment by jimbo-the-prince** [comment]
Exactly this same issue for me. Android 14, Oukitel C51 device, app version 1.2.0, installed using Fdroid. When I receive a call nothing happens onscreen until afterwards when I receive a missed call notification but it's vibrating and yelling like it should for a call. Opening the app doesn't give me any way to answer the call. Display over other apps is on, everything should work afaik but it just doesn't.

**Comment by Esmolante** [comment]
Installed the new version from GP but the problem remains the same, the screen doesn't turn on automatically and, if turned on, no dialog for answering or refusing the call. 
HyperOS 1.0.9

**Comment by Esmolante** [comment]
@anxiouslelimo, thanks for the tip. Unrestricted battery mode and permissions works in my case as a charm. ;)

**Comment by naveensingh** [comment]
I guess this can be closed in favor of https://github.com/FossifyOrg/General-Discussion/issues/268
