### ISSUE TITLE
Call history not updating on the fly

### ISSUE THREAD

**Issue by adarsh1001** [FossifyOrg/Phone#146]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.1

### Affected Android/Custom ROM version

Android 14

### Affected device model

Nothing Phone (2)

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Open the app.
2. Initiate a call from call history screen or the contacts screen.
3. After the call is over, check call history.
4. The contact you dialed won't show up.
5. Force close and restart the app.
6. Now it shows up on the top.

### Expected behavior

Expect the history to be updated in real time.

### Actual behavior

History is only getting updated when opening a fresh instance of the app.

### Screenshots/Screen recordings

https://github.com/FossifyOrg/Phone/assets/8820038/b68c63b6-d1d0-4db3-87b1-d90a46b08a5d

### Additional information

This issue got introduced in 1.1.1 itself.

**Comment by alekksander** [comment]
yes, please fix this one. if my wife is "reporting" this bug to me it means it's real problem for regular people.

**Comment by mezhgano** [comment]
This is crucial bug.
Also, if i add contact via Contacts app, it appears in Phone app only after i reopen it.

**Comment by pled** [comment]
Same here on GrapheneOS, Android 14, Pixel 6a. Very annoying you can't trust your history without restart.

**Comment by Wurftaube** [comment]
Same here on Samsung Note 9, Android 10
Please fix asap! 
Thank you for the Fossify apps!

**Comment by naveensingh** [comment]
Should be fixed in the next update.

**Comment by xyen2001** [comment]
Same here on Xperia Z5. Android 7.1.1. 4G LTE network.

**Comment by naveensingh** [comment]
@e075e For future updates: https://github.com/FossifyOrg/Phone/issues/183
