### ISSUE TITLE
Option to choose the older smaller sized call screen

### ISSUE THREAD

**Issue by Rafee-M** [FossifyOrg/Phone#147]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

There could be an option similar to the "Font Size" setting allowing to choose between the current bigger or previously smaller call screen.

### Why do you want this feature?

> This change has caused issues for small or smaller than average phone sizes. The end call button now overlays existing buttons if the screen is small. Most users will not have this issue but to solve this for everyone, an option in settings to adjust the avatar size would work based on the percentage range you find appropriate.

As mentioned in https://github.com/FossifyOrg/Phone/issues/118#issuecomment-2013889917 it could be usability issue on smaller phones.

The call end button showing while the dialpad is being shown could contribute to that, but I'm unsure to what degree.

The comment mentions having the option to choose the size of the avatar which could be an option instead of just having the choice of the older one.

All in all, having the option to choose the previous smaller screen does 2 things:

1. Provides ease of use of smaller 
2. Customisability

Regards,
R

**Comment by NickAndreou** [comment]
I think the whole concept of having accept and reject buttons is old fashioned and should be abandoned and replaced with gestures.

**Comment by naveensingh** [comment]
The overlapping issue has been fixed and layout is now more responsive to screen sizes. A new version will be released soon.

**Comment by xBassHeadx** [comment]
Nice work. Confirmed fixed.
