### ISSUE TITLE
Support Tellow spammers database

### ISSUE THREAD

**Issue by serrq** [FossifyOrg/Phone#151]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Tellow API integration. Just add a token to have access to a big database containing several blacklisted phone spammers.

### Why do you want this feature?

Because I targeted by telemarketing and spammers.

### Additional information

https://www.tellows.it/?lang=en

**Comment by Aga-C** [comment]
By the design, app has no Internet access, so we can't do this.
