### ISSUE TITLE
We should be able to apply the default sim for calls to the entire contacts.

### ISSUE THREAD

**Issue by yusufsunetci** [FossifyOrg/Phone#155]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I use a dual sim. Every time I want to make a call, an alert comes up asking me with which sim to call. I usually use sim 1. I rarely use sim 2. There is a "Set as default for this contact" option. But it needs to be done one by one for each person. I should be able to make sim 1 the default on calls, instead of doing it individually on each call. There is already call with sim 2 in the options for the people.

### Why do you want this feature?

In order not to repeat the same process every time.

**Comment by Aga-C** [comment]
It's a duplicate of https://github.com/FossifyOrg/Phone/issues/50.

**Comment by yusufsunetci** [comment]
I selected one of the SIM cards as the default SIM in the phone's system settings. When I pressed the call button from the notification, it made a call.

Thanks.
