### ISSUE TITLE
Show a lock icon for blocked numbers in call history

### ISSUE THREAD

**Issue by serrq** [FossifyOrg/Phone#164]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

To better recognize blocked numbers in call history.

### Why do you want this feature?

Improve understanding.

**Comment by Aga-C** [comment]
Currently, blocked numbers don't appear in call history, so there's no need to show them differently or add an option to unlock the number. If you see blocked numbers in your call history, it may be due to this bug: https://github.com/FossifyOrg/Phone/issues/146, so they will disappear once you restart the app.

**Comment by antodc** [comment]
I confirm having the same issue. Unknown numbers appear after restarting. I blocked all unknown numbers, so I suppose they tried to call me.

**Comment by antodc** [comment]
Not a big issue anyway, but I think that in some cases it could be useful to know if some blocked numbers called you. If they disappear from the history, would there be any other way to find that information?
