### ISSUE TITLE
Empty voicemail harassment

### ISSUE THREAD

**Issue by TheR0cketMan** [FossifyOrg/Phone#178]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [x] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.1

### Affected Android/Custom ROM version

Android 14 / HyperOS

### Affected device model

Redmi Note 12 (4g)

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

Receive voicemail, then check said voicemail, delete voice messages so voicemail is completely empty again. Finally wait and it'll followed by constant harassing notifications telling you, that you have a voicemail when you haven't.

If you swipe away the notification, it'll do the same thing. Rinse and repeat.

### Expected behavior

Once voicemail is empty and checked, it should not be doing as explained above until you receive another voice message.

### Actual behavior

Please read the first paragraph.

**Comment by naveensingh** [comment]
@TheR0cketMan 

> Receive voicemail, then check said voicemail, delete voice messages so voicemail is completely empty again

Those actions are not supported in Fossify Phone. Are you sure you are using Fossify Phone?

**Comment by TheR0cketMan** [comment]
> @TheR0cketMan 
> 
> > Receive voicemail, then check said voicemail, delete voice messages so voicemail is completely empty again
> 
> Those actions are not supported in Fossify Phone. Are you sure you are using Fossify Phone? 
> 

![Screenshot_2024-04-28-17-43-46-962_org.fossify.phone.jpg](https://github.com/FossifyOrg/Phone/assets/79772069/0a27c4d4-83f0-4d72-a376-057acfc21912)

I'm definitely using Fossify phone, here's the screenshot to prove it

**Comment by naveensingh** [comment]
> Receive voicemail, then check said voicemail, delete voice messages so voicemail is completely empty again

@TheR0cketMan please share a screen recording for this.

> followed by constant harassing notifications telling you, that you have a voicemail when you haven't.

You can also find the actual app that is sending this notification by long pressing on the notification. I highly doubt it's Fossify Phone.

**Comment by TheR0cketMan** [comment]
> > Receive voicemail, then check said voicemail, delete voice messages so voicemail is completely empty again
> 
> @TheR0cketMan please share a screen recording for this.
> 
> > followed by constant harassing notifications telling you, that you have a voicemail when you haven't.
> 
> You can also find the actual app that is sending this notification by long pressing on the notification. I highly doubt it's Fossify Phone.

I just sent you a screenshot & I know for a fact it's Fossify Phone.

I don't appreciate you calling me a liar and deliberately coming at me like that and causing trouble.

I filed a bug report for the developers to look in to. I can clearly see you aren't one so I suggest staying out of it, mind your own business and let the devs take a look themselves.

**Comment by naveensingh** [comment]
> I just sent you a screenshot & I know for a fact it's Fossify Phone.

That doesn't imply that Fossify Phone is the app sending continuous notifications.

> I don't appreciate you calling me a liar and deliberately coming at me like that and causing trouble.

That wasn't my intent, really. Screen recordings are often helpful in cases like this, we might spot something you did not.

Anyway, I'm closing this because Fossify Phone does not support or handle voicemails. The notification is most likely coming from another app or service or an app disguised as Fossify Phone.

**Comment by TheR0cketMan** [comment]
I know it's from Fossify Phone for a fact. I don't have any other phone app installed and when I tap on the notification to check the voicemail(s) I've received, it takes me directly to Fossify. Voicemails can only be received and checked via Phone apps.

So saying it's invalid and making out it doesn't support voicemail is a load of rubbish.

I opened the issue to try and help as it's clearly a bug which needs looking in to. But sure, if you don't care about your users or your software enough to fix bugs, go ahead and close it.

Looks like I'll have to look for an alternative app. Shame really because Fossify showed promise and I really liked it.

**Comment by antodc** [comment]
@TheR0cketMan Can you try to go to settings -> apps and notifications-> notifications -> notification history , and check whether those notifications actually arrive from Fossify Phone?

**Comment by naveensingh** [comment]
> But for some reason, when tapping on the notification details in the Android status bar it's the default Phone app that will open, hence the confusion here.

Thanks for confirming! I suspected this was the case as the "X missed calls" notification is also created by the Phone Services app. 

> I suggest putting a note in the FAQ about this, as well as a note in the Fossify SMS Messenger FAQ about Class 0 SMS/Flash SMS messages.

Good idea, adding this to my TODO list.
