### ISSUE TITLE
Swiftly searching on the call history screen skips the search results

### ISSUE THREAD

**Issue by adarsh1001** [FossifyOrg/Phone#18]
**Checklist**
 - [x] I can reproduce the bug with the latest version. 
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information to.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
 - [x]  This issue contains only one bug.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Describe the bug**
When the app is opened from cold start and the search term is typed swiftly, the app skips the search results. When typing slowly, the issue doesn't occur.

**To Reproduce**
1. Make Call History the tab to be opened on start in app settings.
2. Open a fresh instance of the app, quickly tap on the search bar and start typing.
3. Valid search results appear for a moment before disappearing.

**Expected behavior**
For valid search results to actually stay rather than disappear.

**Screenshots**
https://github.com/SimpleMobileTools/Simple-Dialer/assets/8820038/74d2a117-3e34-433f-aaf2-954e32267863

**Device info (please complete the following information):**
 - Model: Nothing Phone (2)
 - OS: Android: 14
 - App version: 5.18.1

**Additional context**
Had opened this issue on the [SimpleDialer repo](https://github.com/SimpleMobileTools/Simple-Dialer/issues/660) but that isn't maintained anymore so opening it here since the bug is still reproducible (and quite annoying 😄).

**Comment by naveensingh** [comment]
Should be fixed in the next update.
