### ISSUE TITLE
Fade callEnd button when call is ended

### ISSUE THREAD

**Issue by Melr0k** [FossifyOrg/Phone#181]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Fade the `callEnd` button when the phone call is ended. Why not fade the others as they should not be enabled too…

### Why do you want this feature?

When a phone call ends I don't really understand why it stays there for a bit before the call activity closes. And in this moment I always doubt if the phone call is really ended or not, and it took some time to see the text "Call ended".
I think it's more clear to fade/dim the buttons to reassures that the phone call is ended. And it's easy to do.

### Additional information

I tried `binding.callEnd.setAlpha(0.5f)` in the method `endCall` from `CallActivity` (line 759, just before the `if` statement) and I like it.
It probably should be in its own function so we can visually disable all the buttons we decide to fade.

**Comment by naveensingh** [comment]
Should be fixed in the next update.
