### ISSUE TITLE
Missed call notification displaying only the phone number if it was a person from contact list (sometimes)

### ISSUE THREAD

**Issue by Daniel-RO-TM** [FossifyOrg/Phone#194]
### Checklist

- [ ] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.2.0

### Affected Android/Custom ROM version

Android 13

### Affected device model

Sony Xperia Ace III

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

Just missing a call from a contact and looking at the notification in the bar. I think it depends what contact is calling i guess or its random or else. I did try to reproduce with my mom's calling and its fine, but earlier i missed a call from other contact and only phone number was displayed in notification bar.
PS: had this issue also before the last update.

### Expected behavior

To have the name of the contact displayed in notification when miss a call.

### Actual behavior

With mom calling me its fine it seems, now, but i know it will happen again with other contacts or even her at some point.

### Additional information

Not rooted.

**Comment by Aga-C** [comment]
These notifications are handled by the system, not by Fossify Phone. If you don't see a caller name, you probably saved the contact in Fossify Contacts as a contact not visible for other apps. And we have already the request to handle those notifications: #83.

**Comment by Daniel-RO-TM** [comment]
> These notifications are handled by the system, not by Fossify Phone. If you don't see a caller name, you probably saved the contact in Fossify Contacts as a contact not visible for other apps. And we have already the request to handle those notifications: #83.

I was looking in Fossify Contacts at the contact that didnt display a name and it is saved normally (phone storage) like all the others. Im not saving contacts ”not visible by other apps”. What now ? Thanks

**Comment by Daniel-RO-TM** [comment]
> If you don't see a caller name, you probably saved the contact in Fossify Contacts as a contact not visible for other apps.

You are telling me ”If you don't see a caller name, you probably saved the contact in Fossify Contacts as a contact not visible for other apps.”. I tell you this: ALL my contacts are saved so they can be visible by other apps. Also, i also checked the box in Fossify Contacts to allow other Fossify apps to see private contacts. 

Can you give me another answer?

**Comment by Aga-C** [comment]
As I said in my previous comment, currently we have no control what's displayed in those notifications. Your system is responsible for that. Please wait until someone resolves #83.
