### ISSUE TITLE
XMPP Contact List and Address 

### ISSUE THREAD

**Issue by methuselahin** [FossifyOrg/Phone#195]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Feature description

Is it possible to add a XMPP address tab separately. 

### Why do you want this feature?

Xmpp is widely used in open source community and custom rom users who cares about the functionality and privacy and want to get rid of whatsapp and other data hoggers. 

### Additional information

https://f-droid.org/en/packages/eu.siacs.conversations/ the best example that is there for which the option can be added. There are other forks as well.

**Comment by Aga-C** [comment]
XMPP works via the Internet and, by design, Fossify apps have no Internet permission.
