### ISSUE TITLE
Paste phone number from clipboard into dialpad

### ISSUE THREAD

**Issue by nofishonfriday** [FossifyOrg/Phone#204]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Paste phone number from clipboard into dialpad.

### Why do you want this feature?

There are websites where phone numbers are listed (e.g. service phone numbers), I'd like to copy it from there and paste into dialpad.

**Comment by naveensingh** [comment]
This should work already:
 - Long press on the dialpad text field
 - Click Paste

**Comment by nofishonfriday** [comment]
Ah yes, I didn't try long press, sorry for false alarm and thanks for the quick reply.
