### ISSUE TITLE
Popup to select number when T9 dialing, as it does when using Favourites

### ISSUE THREAD

**Issue by laundmo** [FossifyOrg/Phone#210]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

An option to make clicking the Contact listing in T9 open a popup asking which number to call.

current behaviour:
1. Use T9 to search for contact
2. Click it
3. instantly calls the first listed number

desired behaviour:
1. Use T9 to search for contact
2. click it
3. popup opens to ask for which number to call (Mobile vs Work vs Home etc) like it does for Favourites
4. Calls the selected number

### Why do you want this feature?

Currently, the contact listings in the dialpad (T9) instantly call the first number associated with a contact, not giving me the chance to choose Landline vs Mobile vs Work numbers. This is quite annoying as most contacts i call have multiple numbers and i often need to select which.

this is currently possible with the annoying steps of: long press contact, click "person with magnifying glass" button at the top, select number and call.

### Additional information

This is the popup i'm reffering to which opens from Favourites
![Screenshot_20240703-113033_1_1](https://github.com/FossifyOrg/Phone/assets/24855949/8fd51e51-c679-4d7b-b840-d65f6159f2ec)

**Comment by Aga-C** [comment]
It's another case for https://github.com/FossifyOrg/Phone/issues/102. Please add your remarks there.
