### ISSUE TITLE
Multiple contacts created wich could not be removed

### ISSUE THREAD

**Issue by JozefTheUser** [FossifyOrg/Phone#212]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.2.0

### Affected Android/Custom ROM version

Android 11 , build: HOTWAV_Cyber9Pro_V10.0_S230213

### Affected device model

Hotwav cyber 9 pro

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Open the app
2. Go to contacts wich are found on left bottom of the app
3. See multiple contacts of the same person, as can be seen on pic

### Expected behavior

See the contacts normally without multiplication, I tried to manually remove them but, the appeared once again

### Actual behavior

The app list multiple contacts of the same person, 865 of them but in reality I have 34

### Screenshots/Screen recordings

<img alt="Screenshot_20240709-112114" src="https://github.com/FossifyOrg/Phone/assets/175144450/1be1b70b-d15a-4cb3-bbbf-e443617f4889" width=189 />

### Additional information

- The software of the phone is sometimes laggy
-  I tried multiple contact and dialer apps in order to find most suitable for me
- With the previous contacts app I had problem with unexpected removal of contacs, so I created backup wich  sometimes I had imported multiple times

**Comment by Aga-C** [comment]
> With the previous contacts app I had problem with unexpected removal of contacs, so I created backup wich sometimes I had imported multiple times

It sounds like due to this you've created many duplicate contacts. It's just a phone app, it doesn't manage contacts, so we also don't merge duplicates.
