### ISSUE TITLE
[Feature Request] Option to NOT have Incoming Caller display in Fullscreen

### ISSUE THREAD

**Issue by o-data** [FossifyOrg/Phone#217]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

With incoming call, it display as a Full Screen. Requesting for an option to not to be in full screen, it can be a banner (prefer) or icon instead.

### Why do you want this feature?

1. Not lose track of current thing being use on phone.
2. To check something before answering call. For example, to read a message.
3. Avoid accident "Accept" or "Decline".
4. Screen estate.

**Comment by Aga-C** [comment]
There's already an option `Always display incoming calls on full screen` in Settings.
