### ISSUE TITLE
Support dual sim

### ISSUE THREAD

**Issue by dik23** [FossifyOrg/Phone#22]
Would be great to have dual SIMs supported.  The only dialers I can find with dual SIM support also seem to want to suck my data

I used to own a OnePlus phone and their dual SIM dialer was really useful, it was easy to slide the dialer from SIM1 to SIM2

![dualsim](https://github.com/FossifyOrg/Phone/assets/15139568/a26a993e-a9bb-428e-9412-4ae5f5c2a4a5)

**Comment by chesio** [comment]
@dik23 What do you mean exactly with dual SIM is support? I'm using Simple Dialer with two SIMs without any problems... I would assume the forked version is going to work the same way.

**Comment by Aga-C** [comment]
There is already dual sim support in a Simple Dialer, which this app is a fork of. If you experience some problems with it, please report a bug according to the bug template: https://raw.githubusercontent.com/FossifyOrg/Voice-Recorder/master/.github/ISSUE_TEMPLATE/bug_report.md
