### ISSUE TITLE
Merge with Contacts

### ISSUE THREAD

**Issue by PhilippKosarev** [FossifyOrg/Phone#221]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Fossify Phone and Contacts largely mirror each other's functionality already.
My reasoning is - why have two apps which mirror each other's functionality when it would be less work implementing features in one app rather than two, which would allow for the development to speed up.

### Why do you want this feature?

I personally have to have Contacts and Phone on my home screen which feels like a needless waste of space.

### Additional information

To allow for this, currently, this would require the make the dialpad a separate page on the nav bar to free up the FAB.
This would leave us with 5 tabs (Dialpad, Contacts, Favourites, Groups and Call history), which is not ideal.
Concerning the Favourites tab, I see 2 ways to solve this.
1. Making groups (which are in Fossify Contacts) expandable instead of opening on a separate page. This would allow to make Favourites a group which is expanded by default.
2. Display Favourites at the top of the Contacts page.

This leaves us with 4 tabs which is much more acceptable. We could also move the Call history to the 3 dot menu at the top, but I digress.

**Comment by chesio** [comment]
Hi @PhilippKosarev, this has already been requested (and extensively discussed) before - see: https://github.com/FossifyOrg/Phone/discussions/13
