### ISSUE TITLE
Online Sync and Backup the History Call Log Feature request 

### ISSUE THREAD

**Issue by mahdiaqallal** [FossifyOrg/Phone#223]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

To enhance this great app I would like to propose a feature :

Online Sync and Backup the History Call Log

### Why do you want this feature?

It will add seemless:
- security and recovery by scheduled / on demand syncing and backup (lost device)
- privacy by having an off device online backup of the history call log
- easier switch to a new device (update, change, recovery) by uploading the latest or chosen scheduled / on demand file stored or retrieved from online storage

### Additional information

Would be great if:
- the default backup name would include the date/time and Device name or model type

- even greater if one could, through settings, define the custom name of the backup files with fields (date, time, device name, device model, etc...)

I thing it might have helped this feature request description , but I can't sketch any rabbit picture :)

**Comment by Aga-C** [comment]
By the design, app has no Internet access, so we can't do this. There's already an offline call log backup feature if someone needs it.
