### ISSUE TITLE
Contact Names Not Displaying and Call Handling Problems

### ISSUE THREAD

**Issue by rjrajujha** [FossifyOrg/Phone#230]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [ ] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [ ] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [ ] This issue contains only one bug.
- [x] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.2.0

### Affected Android/Custom ROM version

Android 14

### Affected device model

OnePlus

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. **Save a Contact:** Add a contact in Fossify Contacts.
2. **Receive a Call:** Wait for an incoming call from the saved contact.
3. **Observe Display:** Check the name displayed during the call; it may show only the number.
4. **Call Management:** Try to swipe or merge calls for conferencing and note the app's behavior.

### Expected behavior

- **Accurate Contact Display:** The contact's name should appear correctly instead of just displaying the phone number (e.g., `+919876XXXX - work` or `+919876XXXX - mobile`).
- **Seamless Call Handling:** Swiping and merging calls for conferencing should work smoothly without any lags or disconnections.

### Actual behavior

- **Incorrect Display:** Some contacts are showing the phone number instead of the contact name.
- **Call Handling Issues:** The app is experiencing lags or disconnections while swiping or merging calls for conferencing.

### Additional information

- **Show CallerID Feature:** Currently implementing a feature to display CallerID during incoming calls using a Telegram bot with API and secret keys. The bot `@TrueCaller_Z_Bot` is functioning perfectly for this purpose.
  
- **Call Recording:** Exploring the feasibility of adding a call recording feature to the app.

**Comment by n-ce** [comment]
I can confirm this. Conference call disconnection issues. Please re-open this. @Aga-C

**Comment by rjrajujha** [comment]
@Aga-C 

The "CallerID Feature" mentioned in the issue report can be ignored, as it's not integrated into Fossify and there's no plan for it. However, the problem of contact names not displaying correctly in the call log is a genuine bug. Specifically, when saving multiple numbers under one contact (e.g., `+919876XXXX` as "Work" and `+916789XXXX` as "Home" for a contact), one of these numbers often shows up as a number instead of the contact name in the call log.

I want to note that I haven't noticed this issue with contacts stored in the phone's default contact storage—only when the contacts are saved in Fossify's private contacts storage. The issue occurs with some contacts, especially those with multiple numbers under one contact, but not with all contacts.

Additionally, the "Conference call disconnection issues" mentioned by @n-ce need to be addressed as they impact the user experience during call handling.

Please look into these issues. Thank you!
