### ISSUE TITLE
fastlane changelog much too long

### ISSUE THREAD

**Issue by IzzySoft** [FossifyOrg/Phone#231]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.2.0

### Affected Android/Custom ROM version

n/a

### Affected device model

n/a

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

Just look at the changelog, it is truncated

### Expected behavior

Changelog within limits (max 500 char)

### Actual behavior

Changelog over limit (915 char)

### Screenshots/Screen recordings

![image](https://github.com/user-attachments/assets/38cd07e8-74d3-404b-8fda-13e55726e3e3)

### Additional information

For this one, I've simply truncated the file more sanely (before the truncated line) and added a "and more" at the end. But please take care to stay in limits here.

**Comment by Aga-C** [comment]
It already has been fixed: https://github.com/FossifyOrg/Phone/commit/b47ac1f30469ac7e0936fd9040e5f0d271f96d5d.

**Comment by naveensingh** [comment]
Will issue an update with a smaller changelog soon.

**Comment by IzzySoft** [comment]
The one already here is "past" (won't be pulled again, at least not at IzzyOnDroid – and on F-Droid it doesn't matter as when they pull it next time, it's become obsolete and won't be used). So this is mostly about "future versions" :wink: Thanks!
