### ISSUE TITLE
No dial list shown (empty)

### ISSUE THREAD

**Issue by Reinbeker73** [FossifyOrg/Phone#233]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

Version 1.2.0

### Affected Android/Custom ROM version

Android 14

### Affected device model

Nokia G22

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. New Installation from predecessor SP
2. No backup from SP
3. No entriss in dial list in FP

### Expected behavior

FP creates a new list oft call history

### Actual behavior

No dial or call list is created.
Neither self dialing entries from contacts nor incoming calls.

### Screenshots/Screen recordings

![Screenshot_20240820-193313](https://github.com/user-attachments/assets/f2efa398-9920-40e6-a589-6780e693ab97)

### Additional information

Backups from predecessors Simple Massage and Simple Contacts were taken. No problems to put in data in new Fossify apps.
Cache cleaned, all authorisations set.

**Comment by Aga-C** [comment]
1. Do you have anything in Contacts and Favorites tabs?
2. Can you see call history in a stock dialer app?

**Comment by Reinbeker73** [comment]
1. Yes. Contacts and Favorites no problem, there are entries.
2. Neither with stock dialer app.

**Comment by Aga-C** [comment]
If a stock dialer app also doesn't show it and the `read call log` permission has been granted, it means that there's no call history on your phone. Our app (and Simple Dialer) doesn't keep its own call history, we just display the phone's one, so you should see the same entries with any phone app.

**Comment by Reinbeker73** [comment]
Thanks. The question is, why the app dies not creates a new call history in a new .json file?
I got new calls which do not appear.

**Comment by Aga-C** [comment]
Why the app should export call history every time it's closed? Fossify Phone uses the system's call history, it doesn't keep its own, so if new calls don't appear, that's likely an OS issue or another app clears it.

BTW. There's already a request for automatic backup of call log: https://github.com/FossifyOrg/Phone/issues/224.
