### ISSUE TITLE
Occasional misbehavior where screen lock overrides full screen call notification while being called

### ISSUE THREAD

**Issue by miphilip** [FossifyOrg/Phone#239]
### Checklist

- [ ] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.2.0

### Affected Android/Custom ROM version

Android 13

### Affected device model

Samsung galaxy a32

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

Recieved a call while phone was charging and locked with PIN

### Expected behavior

Screen lock should be temporarily disabled by the app when being called and re-enabled after. Maybe the "disable screen lock permission" could help

### Actual behavior

Occasionally phone rings only to show lock screen. So i have to first unlock phone to see who is calling

**Comment by Aga-C** [comment]
It seems to be the same bug as https://github.com/FossifyOrg/Phone/issues/165. If you'd like, you can describe your case there.
