### ISSUE TITLE
Confirmation is not asked if the call is initiated from android stock contacts

### ISSUE THREAD

**Issue by AnthillSudoku** [FossifyOrg/Phone#243]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.2.0

### Affected Android/Custom ROM version

eOS 2.3 (android 13)

### Affected device model

samsung a52q

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Open Fossify Phone
2. Enable "show a call confirmation dialog before initiating a call" in the settings
3. Open android stock contacts app
4. Call a contact

### Expected behavior

A confirmation dialog appears

### Actual behavior

Call start immediately

### Additional information

I always used fossify contacts + fossify phone and removed stock contacts, so I did not have this issues since I tried reinstalling stock, as users may use other contact apps.

I am not sure if it is related with https://github.com/FossifyOrg/Phone/issues/240#issuecomment-2366092373

However this setting should be respected regardless of who invoke Fossify Phone

**Comment by naveensingh** [comment]
> this setting should be respected regardless of who invoke Fossify Phone

Showing a confirmation dialog is the responsibility of the app initiating the call.

Under the hood, apps place calls using a `ACTION_CALL` intent which is then directed to the default phone app. `ACTION_CALL` is supposed to directly place a call without any confirmation dialog. Hijacking the `ACTION_CALL` intent to show a confirmation dialog would cause problems like:

- Duplicate confirmation dialogs when using both Fossify Contacts and Phone with this setting enabled. This can be solved but see next point.
- App will keep waiting for call confirmation when a call is placed using some safety/emergency app gesture.
