### ISSUE TITLE
old feature req:  Dialed number or code should remain after dial

### ISSUE THREAD

**Issue by harry-osborn1** [FossifyOrg/Phone#244]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

In previous versions (1.0.0 & 1.1.1) when we dail a number to call or dial a code then after dialing code or making a call, the number or code remains there (it was useful because many times code does not work and show error message then again we have to type code again) it is not in 1.2.0 so, I request you please bring back this feature (thing) in next update [you can add an on/off button in setting if possible so if someone wants to turn on they can.

*Showing code even after dialing in 1.1.1*

![Screenshot_20240926-063321](https://github.com/user-attachments/assets/05d87ba3-452a-4f4b-9a17-d07fd11b0525)
![Screenshot_20240926-063356](https://github.com/user-attachments/assets/b120e4c9-529d-4baa-99c5-9e8d2cda617c)

*Not showing code after dialing in 1.2.0*

![Screenshot_20240926-063143 (1)](https://github.com/user-attachments/assets/634ace3c-9241-4123-9eb2-86de4d379f09)
![Screenshot_20240926-063238](https://github.com/user-attachments/assets/b5f478b7-ae38-48b2-9c16-8491273b5a3c)

### Why do you want this feature?

Because It saves our time and effort.

**Comment by antodc** [comment]
@harry-osborn1. Have you tried tapping the call button? Your request seems rather similar to #60.

**Comment by naveensingh** [comment]
I guess this can be closed unless peter's friend has a use-case we haven't considered.

**Comment by harry-osborn1** [comment]
> @harry-osborn1. Have you tried tapping the call button? Your request seems rather similar to #60.

So Sorry for the late reply, I tried tapping the call button and yes it works perfectly for a phone number, I mean it returns phone number back, But it doesn't work for USSD code. It doesn't return USSD code.

**Comment by antodc** [comment]
I tried *#*#4636#*#* (internal phone statistics) before posting my suggestion and it works. So, I thought it would work for any 'strange' code, but indeed with *99# it does not. I also tried with ##002# (to stop call transfers) and got the same negative result.

**Comment by antodc** [comment]
Do not know why, but the codes I write are changed by the Github editor. The codes I used are "asterisk hash asterisk hash 4636 asterisk hash asterisk hash" and "hash hash zero zero two hash".

**Comment by harry-osborn1** [comment]
> I tried "*#*#4636#*#*" (internal phone statistics) before posting my suggestion and it works. So, I thought it would work for any 'strange' code, but indeed with "*99#" it does not. I also tried with "##002#" (to stop call transfers) and got the same negative result.

*99# is a sim code which will only work for me. [I'm just saying sometimes I type long code like (*3100*3*0*0*9*2*4# this code is for checking sim number) sometimes I get errors so again I have to type the whole code in new version of Dialer app but in old version if I get any error it doesn't empty from dialer so I just use it again without typing, that's I requested that this should be in new version of Dialer app plz.
