### ISSUE TITLE
Ability to add contacts in-app

### ISSUE THREAD

**Issue by TheSmilingTurtle** [FossifyOrg/Phone#25]
When pressing the "+" button to add a contact, the app brings up the following dialog:

![Screenshot_20240116-023654_1.png](https://github.com/FossifyOrg/Phone/assets/59168627/0f4981ab-5226-42d1-bc13-c51cc96b65d2)

It would be nice if this could be done in-app.

**Comment by Aga-C** [comment]
It brings up because it's a responsibility of the contacts app, not the phone app. If you'd like to have them merge, check this discussion: https://github.com/FossifyOrg/Phone/discussions/13.

**Comment by TheSmilingTurtle** [comment]
Oh, terribly sorry, I remembered the same vote from reddit where the vote came out to be yes. In that case everything is fine :)
