### ISSUE TITLE
Block contacts wildcard

### ISSUE THREAD

**Issue by m2nis** [FossifyOrg/Phone#251]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Hello,

In order to block unwanted calls, I'm a avid user of the block list. I already use the joker to block a large number of concurrent numbers, like for example : 
012345*
to block all the numbers beginning with 012345.

The problem is that sometimes the caller will present a number sometimes like 0123456789 (France in my case), sometimes a number like +33123456789.

At this time, I then need to enter 012345* AND +3312345* in the list of blocked contacts to be sure to block them all.

Will it be possible to have the option to enter something like (+33|0)12345* to have a single line ?

Thank you.

### Why do you want this feature?

See above.

**Comment by naveensingh** [comment]
I think the app should strip the country code before checking the pattern.

The implementation is simple but pattern blocking (unofficially and kind of) supports regular expressions so in your specific case, you can try `^(0|+33)12345*` or its less accurate version `*12345*`.

**Comment by m2nis** [comment]
As far as I know, the support of regular expression is very limited and `^(0|+33)12345*` shouldn't work. In fact, it is impossible to even type this expression because the keyboard is limited to numeric input.

`*12345*` could work but will stop far too much numbers. 0123456789 will be stop, but 0212345678 as well, and it's a problem.

**Comment by naveensingh** [comment]
> In fact, it is impossible to even type this expression because the keyboard is limited to numeric input.

It should be fixed but that's why I said it's "unofficially" supported, you can always paste anything into the text field:

<img src="https://github.com/user-attachments/assets/45c1aa0c-3cc5-4240-b65b-3ffd0648496d" width=264 /> <br>


> the support of regular expression is very limited and ^(0|+33)12345* shouldn't work.

The provided expression should work fine. Here's the code:

https://github.com/FossifyOrg/Commons/blob/9be479f97a2a0c0f80c0464bbf83ca552dde7507/commons/src/main/kotlin/org/fossify/commons/extensions/Context.kt#L1134-L1145

I'm not dismissing your request, I'm saying it needs to be reworked so it doesn't require one to create complex patterns.

**Comment by m2nis** [comment]
Great ! Looks nearly perfect. ;-)

In fact, there are several difficulties. As you say, how to easily treat the country, according to the fact that people can have different countries with may be different rules (in France, it's "+33" or "0" (or "0033"), but how in the others ?).

Another point is how to save these rules easily ? Will it work if we put the expressions in a contact ?

Thank you for your reply.
