### ISSUE TITLE
Rule based ringtone selection

### ISSUE THREAD

**Issue by xandro0777** [FossifyOrg/Phone#256]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Would be very nice to have ringtones(or no ringtone) according to rules like:
* specific ringtone selected in contacts 
* member of a group known by contacts
* known number from contacts (or likely prefix with local extension)
* local region prefix
* some other area codes that may be of special interest 
* anything else 

### Why do you want this feature?

Is a bit cumbersome to assign a ringtone to every single contact and impossible to specify ringtones for local area and such 

### Additional information

Somewhat related to 
* https://github.com/FossifyOrg/Phone/issues/65
* https://github.com/FossifyOrg/Phone/issues/31
* https://github.com/FossifyOrg/Phone/issues/236

**Comment by Aga-C** [comment]
Can you edit your request (and title properly) to limit your request only to specific things that aren't currently supported by the app and aren't raised in other requests? Because:

> specific ringtone selected in contacts
member of a group known by contacts

It's handled by the system itself. If it doesn't work for you while using Fossify Contacts, these are known bugs and already reported.

> known number from contacts

It's the same as `different ringtone from unknown caller` which you've linked.

**Comment by xandro0777** [comment]
@Aga-C : thanks for your comments, my editing abilities on this smartphone are not stellar so I will edit later. Did not know it is possible to add ringtones to groups.

Also, while some features have already been requested or may already work this is a more general idea for handling those things so it might still make sense to list everything here once again (and with reference to the related issues)

Just realized, it would be also nice to have rules to block some/most calls during the night or while driving.

**Comment by Aga-C** [comment]
> Also, while some features have already been requested or may already work this is a more general idea for handling those things so it might still make sense to list everything here once again (and with reference to the related issues)

We want to keep specific requests in `Issues`, that's why you had to check `This issue contains only one feature request.`. [Discussions](https://github.com/FossifyOrg/Phone/discussions) are a better place for general ideas.

> Just realized, it would be also nice to have rules to block some/most calls during the night or while driving.

If you'd like it, please create a separate request.
