### ISSUE TITLE
Show public names related to phone numbers

### ISSUE THREAD

**Issue by parrenin** [FossifyOrg/Phone#258]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I recently switched to Fossify phone, it is very well done, congrats!
One thing I miss from the Google dialer is the display of public names related to phone numbers.
I suppose the Google dialer looks in the Google Maps database and find a name related to the number you are dialing.
This is handy, since even though the number is not in your addressbook, the name appears when you dialing to that number.
I am wondering if such a feature could be implemented in Fossify/phone.

### Why do you want this feature?

It is convenient to have the name appearing when you compose a public number.

**Comment by Aga-C** [comment]
By the design, the app has no Internet access, so we can't do this.

**Comment by parrenin** [comment]
OK, thanks for the reply.
What is the problem with having an optional internet access?

**Comment by Aga-C** [comment]
> Internet permission is probably the most misused permission in all of history so unless the app's core functionality requires Internet permission, we won't add it. That means all of the existing apps will never get access to the internet.

https://github.com/orgs/FossifyOrg/discussions/68#discussioncomment-8001994
