### ISSUE TITLE
[Feature Request] Allow User to Use Other Feautures of App During Call

### ISSUE THREAD

**Issue by Tahinli** [FossifyOrg/Phone#270]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Hi,

Allow user to check latest calls and contacts during calls.

### Why do you want this feature?

Today I was talking with some customer service and in that time I needed to check my latest phone calls to ask question but I didn't. Because I was using Phone app for actually talking with customer service and couldn't find a way to turn back and check logs.

**Comment by Aga-C** [comment]
It's possible. Press Android's back button during a call and:
- If you've received the call, it will navigate you out of the app. Then enter the Phone app from your launcher to show its main screen. 
- When you're doing the call from the app, the back button will navigate you straightly to the previous screen. 

Then, if you want to go back to the call, just press the notification.

**Comment by Tahinli** [comment]
For user experience, if you have a chance can you add back button for call screen. If you didn't say that I'm able to back via back button of Android I might not be able to think about it.
