### ISSUE TITLE
Call Recording Feature

### ISSUE THREAD

**Issue by Lorograch1** [FossifyOrg/Phone#273]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Option for call recording just like in google or mi phone. And alsp, option for selcting to record calls always, and not just pressing on the option during the call. 

### Why do you want this feature?

I feel its a very important feature that can cater to various needs.

**Comment by chesio** [comment]
This has already been requested multiple times - see: #17

But please don't add yet another "+1" comment there, thumbs up on the issue post is enough ;-)
