### ISSUE TITLE
Banning Satellite Calls

### ISSUE THREAD

**Issue by Reaper1A** [FossifyOrg/Phone#285]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Banning/Blocking all Incoming Satellite calls.
Banning/Blocking all Outgoing Satellite calls.

### Why do you want this feature?

Was getting calls from unknown numbers first. Now getting unknown calls from international numbers if that is not bad enough got an unknown call from a satellite number. Hence this request. Thanks

**Comment by Aga-C** [comment]
You can already do it. Go to Settings → Manage blocked numbers, and add the rule `+88*`. It should block all calls from satellite phones.
