### ISSUE TITLE
Change the Shape of the Search Box Background

### ISSUE THREAD

**Issue by brucetheelephant** [FossifyOrg/Phone#29]
**Checklist**
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**
This is more of an annoyance. The Search Box Background has no corners, it ends in semicircles (in most of the apps). I don't like this!

**Describe the solution you'd like**
I would like for the Search Box Background to have round corners.

**Describe alternatives you've considered**
I have tried making the background "disappear" by setting the app Primary Color to be the same as the Background Color but then the app Main Tab "disappears" into the Tab Bar.

**Additional context**
Here's an example of how I would like the Search Box to look:

![Screenshot_2024-01-17-17-07-33-437_com pcloud pcloud_1](https://github.com/FossifyOrg/Phone/assets/112579709/1a0d1ba6-56a0-446b-b6e2-8a5853d31bcf)

Thanks for reading this! : )

**Comment by Aga-C** [comment]
Please raise issues regarding all apps in https://github.com/FossifyOrg/General-Discussion/issues.
