### ISSUE TITLE
Add CallerID: YetAnotherCallBlocker, Google, opencnam

### ISSUE THREAD

**Issue by Rexadev** [FossifyOrg/Phone#32]
**Checklist**
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**
Yes, I miss google spam filter in degoogled phone.

**Describe the solution you'd like**

**Describe alternatives you've considered**

https://gitlab.com/xynngh/YetAnotherCallBlocker/

**Additional context**

**Comment by Aga-C** [comment]
App doesn't have an Internet access, so it won't have such feature. However, you can use YetAnotherCallBlocker as a separate app with Phone, works like a charm.

**Comment by vertigo220** [comment]
YACB is abandoned and hasn't been updated for two years.
