### ISSUE TITLE
Update Icons for Missed, Received, OutgoingCalls

### ISSUE THREAD

**Issue by Rexadev** [FossifyOrg/Phone#33]
~Show Arrow for missed, Received, Outgoing calls in Call History~
**Checklist**
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

## Icon suggestion from fonts.google.com/icons but color needs to be added

North East - ![north_east_FILL0_wght400_GRAD0_opsz24](https://github.com/FossifyOrg/Phone/assets/62152714/468ccd63-f535-4163-bc8e-42c4647660d3)
Call Missed - ![call_missed_FILL0_wght400_GRAD0_opsz24](https://github.com/FossifyOrg/Phone/assets/62152714/c60fd0e0-8fad-4e7a-978a-e8411bf3050f)
Phone Missed ![phone_missed_FILL0_wght400_GRAD0_opsz24](https://github.com/FossifyOrg/Phone/assets/62152714/3c68118e-cf50-43ba-b931-7c1da7f27c08)
South West  ![south_west_FILL0_wght400_GRAD0_opsz24](https://github.com/FossifyOrg/Phone/assets/62152714/f95a8dce-1d17-4168-b902-0cc50d645098)

**Is your feature request related to a problem? Please describe.**
Obviously a very important feature missing

**Additional context**
![image](https://github.com/FossifyOrg/Phone/assets/62152714/6d60bf5e-e32c-436a-b0fa-8e884a5c5cf9)

**Comment by Aga-C** [comment]
In the Call History tab, there are already such icons (not just an arrow, but it still symbolizes the same thing).

**Comment by Rexadev** [comment]
> In the Call History tab, there are already such icons (not just an arrow, but it still symbolizes the same thing).

Icons should be changed for example outgoing should be a simple green North-East Arrow, phone icon is wierd

@Aga-C

**Comment by Rexadev** [comment]
Also instead of different icons for same contact (example contactX miss call, outgoing,...), it shows same contact many times
@Aga-C

**Comment by Aga-C** [comment]
> Icons should be changed for example outgoing should be a simple green North-East Arrow, phone icon is wierd

We will think about it and reopen the issue if needed.

> Also instead of different icons for same contact (example contactX miss call, outgoing,...), it shows same contact many times

If you want to group calls from the same number, there is an option `Group subsequent calls with the same number at the call log`. If it doesn't work correctly, please raise a bug.

**Comment by Rexadev** [comment]
"Group subsequent calls with the same number at the call log" is working but it need improvements.
If there is a mix of  miss call, outgoing, incoming it shows PhoneNumber(X) where is number of calls, If there where arrows it would be nice.


@Aga-C

**Comment by Rexadev** [comment]
@Aga-C please reopen this issue

**Comment by Aga-C** [comment]
If you want this issue to be reopened before we decide if we'd like such a change, please remove `[Reopen this]` in the title, and write in the description what you want to be done, but according to the current state of the app. Currently, the description can be understood as: "there are no icons".

**Comment by Rexadev** [comment]
> If you want this issue to be reopened before we decide if we'd like such a change, please remove `[Reopen this]` in the title, and write in the description what you want to be done, but according to the current state of the app. Currently, the description can be understood as: "there are no icons".

please check

**Comment by Rexadev** [comment]
![north_east_FILL0_wght400_GRAD0_opsz24](https://github.com/FossifyOrg/Phone/assets/62152714/468ccd63-f535-4163-bc8e-42c4647660d3)
![call_missed_FILL0_wght400_GRAD0_opsz24](https://github.com/FossifyOrg/Phone/assets/62152714/c60fd0e0-8fad-4e7a-978a-e8411bf3050f)
![phone_missed_FILL0_wght400_GRAD0_opsz24](https://github.com/FossifyOrg/Phone/assets/62152714/3c68118e-cf50-43ba-b931-7c1da7f27c08)
![south_west_FILL0_wght400_GRAD0_opsz24](https://github.com/FossifyOrg/Phone/assets/62152714/f95a8dce-1d17-4168-b902-0cc50d645098)

**Comment by Rexadev** [comment]
@Aga-C I added icon icon suggestions in main thread please check

**Comment by chesio** [comment]
I actually prefer current icons that include phone graphic as well - this way it's easier for me to differentiate between incoming call (arrow pointing to the phone) and outgoing call (arrow pointing from the phone). But I guess it's a matter of habit.
