### ISSUE TITLE
Sort call history by Today, Yesterday, Week, Month, Other

### ISSUE THREAD

**Issue by Rexadev** [FossifyOrg/Phone#36]
**Checklist**
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**
Makes it look clean easy to find contacts

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![image](https://github.com/FossifyOrg/Phone/assets/62152714/0f45e246-7c46-4b1b-bd05-5f80704e9970)

**Comment by inson1** [comment]
what about this year?

**Comment by inson1** [comment]
and do you mean week etc.  from (Monday to Sunday (if Sunday is your last day))  or if today is Friday then Friday to Thursday?

If first there should be switch for monday vs Sunday as start of the week

**Comment by Rexadev** [comment]
@inson1 

Mon to Mon

**Comment by inson1** [comment]
@Rexadev that would be more than week. 8 days.

**Comment by naveensingh** [comment]
This was implemented to resolve https://github.com/FossifyOrg/Phone/issues/96.
