### ISSUE TITLE
PRIORITY reproduceable rebuilds

### ISSUE THREAD

**Issue by milkcreeks** [FossifyOrg/Phone#37]
**Checklist**
 - [√ ] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [ ]  I have read the FAQ and my problem isn't listed.
 - [√ ]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [√ ]  This issue contains only one feature request.
 
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when apps cannot be trusted by verification using a reproduceable rebuilds subset of David A. Wheeler's DDC Thesis for DoD militre software.

**Describe the solution you'd like**
A clear and concise description: I reccomend PRIORITY in the first for a development feature of reproduceable rebuilds from sourcecode - apk for all of Fossify line of apps.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. This intent was slated to proof against SimpleMobileTools and not yet complete. verification.f-droid.org appears to have began yet failed to provide a similar solution.

**Additional context**
Add any other context or screenshots about the feature request here. For a full rubrick see David A. Wheeler's Thesis on mitigating trusting trust.

**Comment by Aga-C** [comment]
Here's an issue about this: https://github.com/FossifyOrg/General-Discussion/issues/7. If there are any problems with reproducible builds, comment there.
