### ISSUE TITLE
[Duplicate] Merge Contacts and Phone

### ISSUE THREAD

**Issue by Rexadev** [FossifyOrg/Phone#52]

**Comment by naveensingh** [comment]
There's already a poll: https://github.com/FossifyOrg/Phone/discussions/13

**Comment by Rexadev** [comment]
@naveensingh why vote when we can discuss

**Comment by naveensingh** [comment]
A: The poll wasn't my choice.
B: You can discuss it there as well because it's a discussion + poll (best of both worlds).
