### ISSUE TITLE
Upstream metadata feature from Simple Contacts Pro SE.

### ISSUE THREAD

**Issue by Rexadev** [FossifyOrg/Phone#53]
https://github.com/stephanritscher/Simple-Contacts

> This extended version ([F-Droid](https://f-droid.org/packages/de.ritscher.simplemobiletools.contacts.pro/), [GitHub](https://github.com/stephanritscher/Simple-Contacts)) of Simple Contacts Pro ([F-Droid](https://f-droid.org/en/packages/com.simplemobiletools.contacts.pro/), [GitHub](https://github.com/SimpleMobileTools/Simple-Contacts)) supports separate address fields for post office box, apartment/suite, street, city, zip code, state and country name.
The extension makes the app compliant with other applications (e. g. Thunderbird with CardBook, iOS Contacts) and cloud services (e. g. Nextcloud) that support the CardDAV and vCard standards (RFC 6352, RFC 6350).

Related to https://github.com/FossifyOrg/Phone/issues/42

**Checklist**
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Comment by Rexadev** [comment]
> Related to #42

But it is related to the problem https://github.com/FossifyOrg/Phone/issues/42

**Comment by Rexadev** [comment]
@stephanritscher Would you please tell @Fossify that they are allowed to use your code

**Comment by Aga-C** [comment]
We know it's related to that problem, but it doesn't mean that we can accept issues like "copy code from someone else". We're open to contributions, so if someone wants to move that feature and has the original author's approval, that's ok for us.
