### ISSUE TITLE
Call in notificaton 

### ISSUE THREAD

**Issue by DeadSecTr** [FossifyOrg/Phone#55]
Translate to English:

Please fix that one can only hang up by pressing the red phone symbol and not otherwise... as often accidentally hangs up the call when trying to maximize the phone app from the notification (see att.![Screenshot_20240123-220430.png](https://github.com/FossifyOrg/Phone/assets/90558189/9396ac29-faf6-4a46-bd3e-ad1cc1174260)

 picture)

**Comment by Aga-C** [comment]
If you have problem with accidental hang-ups from notifications, there is an option in Settings `Always display incoming calls on full screen`. Calls will then always appear on the full screen, so you can only hang up them by swiping.

**Comment by inson1** [comment]
@Aga-C I think that is good request if that is possible you should only hang up by clicking on the button, right?

**Comment by Aga-C** [comment]
@inson1 What do you mean? Now, when call notification happens, the only way to hang up is by clicking on the button.

**Comment by inson1** [comment]
@Aga-C Look at the image, that is more then hang up image, better wording would be that the button is bigger then the image, but Im not sure if that can be fixed

**Comment by DeadSecTr** [comment]
> If you have problem with accidental hang-ups from notifications, there is an option in Settings `Always display incoming calls on full screen`. Calls will then always appear on the full screen, so you can only hang up them by swiping.

That not a solution! Why you closed this?

**Comment by DeadSecTr** [comment]
I mean NOT a incoming call...i mean ongoing call...look at the image bruh...

**Comment by Aga-C** [comment]
@DeadSecTr That's why you should fill the template and explain what you mean. Just adding an image with a very rough description isn't enough to verify if the issue is valid.

Please fill the template and maybe even make the suggestion what you'd like.

**Comment by Aga-C** [comment]
@DeadSecTr I am closing this issue because it didn't comply with old issue template, wasn't fixed and some time ago we've moved to issue forms. If you still want this issue to be open, please raise a new issue with a properly filled form.
