### ISSUE TITLE
Getting a call and knowing if it is a scam or not

### ISSUE THREAD

**Issue by Shadow-Hunt3r** [FossifyOrg/Phone#59]
**Checklist**
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**
I constantly keep getting scam calls that promptly hangup when I'm waiting for an important call so I start ignoring calls from unknown number just to be surprised as to why someone didn't call me

**Describe the solution you'd like**
Whenever receiving a call then the app shows under the phone number if it is a known scam caller using a quick lookup if the user is connected to the internet and possibly a rough area of where the call would be through the likes of a phone lookup in case that the number isn't 

**Describe alternatives you've considered**
At least a small concise method where a known scam caller could be flagged to help prevent scam calls all around the world

**Additional context**
Information from sites such as [UK Whocalled](https://who-called.co.uk/), [US Whocalled](https://who-called.us/) being used as a resource to find out if the phone number is a known scammer based on previous reports

**Comment by Aga-C** [comment]
See: https://github.com/FossifyOrg/Phone/issues/32#issuecomment-1898951623.

**Comment by inson1** [comment]
apps have no internet access
fr for area https://github.com/FossifyOrg/Phone/issues/39 (in history, but could be reused)

we could create script for creating list of spam numbers from that websites maybe, but I think that is out of scope of tis project
