### ISSUE TITLE
Contact images in incoming/outgoing calls is very low resolution

### ISSUE THREAD

**Issue by adarsh1001** [FossifyOrg/Phone#6]
**Checklist**
 - [x] I can reproduce the bug with the latest version. 
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information to.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
 - [x]  This issue contains only one bug.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Describe the bug**
Assign image to a contact. On calling them or receiving their calls, the image shown is very pixelated.

**To Reproduce**
1. Open the app and go to the Contacts tab.
2. Assign a high resolution image to a contact.
3. Call them.
4. The image shown while calling will be pixelated.

**Expected behavior**
For the image to not lose its quality.

**Screenshots**
Assigned an image to a contact, notice how clear it is.
![Screenshot_20231227-200102.png](https://github.com/FossifyOrg/Dialer/assets/8820038/2c8beff9-2385-48f3-96e3-b1394076d7c2)

While calling the contact:
![Screenshot_20231227-200114.png](https://github.com/FossifyOrg/Dialer/assets/8820038/2ed8a45a-7fe6-438d-8fd7-dedfd0f97440)

**Device info (please complete the following information):**
 - Model: Nothing Phone (2)
 - OS: Android 14
 - Version: 5.18.1

**Additional context**
N/A

**Comment by Aga-C** [comment]
@adarsh1001 How the contact is stored? Is it a private contact or in the phone storage?

**Comment by adarsh1001** [comment]
@Aga-C it's in the Phone Storage.
