### ISSUE TITLE
quick dial back in dialpad

### ISSUE THREAD

**Issue by nehemiagurl** [FossifyOrg/Phone#60]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

In the dialpad window, clicking the "call" button with no number typed in should bring up the most recent number from the "call history" tab.
See for example this behavior from Samsung's default dialer, which works exacly as described:

https://github.com/FossifyOrg/Phone/assets/109424320/680f09c9-22dd-4240-b4eb-b522aa1d3334

### Why do you want this feature?

This speeds up returning a call, or calling someone again after you've hung up but realise you forgot to say something.

### Additional information

This is especially helpful when "open dialpad by default" is on, as it saves multiple button presses to get to the "call history" tab.

**Comment by naveensingh** [comment]
I need this too, thanks!

**Comment by naveensingh** [comment]
It'll available in the next update.
