### ISSUE TITLE
[Regression] Call log doesn't show number as contact if the no. is saved with spaces.

### ISSUE THREAD

**Issue by Rexadev** [FossifyOrg/Phone#61]
#### Checklist
- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

#### Affected app version
1.0.0

#### Affected Android/Custom ROM version
Android 11

#### Affected device model
vince

#### How did you install the app?
GitHub releases

# Steps to reproduce the bug
1. Try to save many (3) numbers in 1 contact.
2. Set one as favorite (I did the bottom one)
3. Name them custom (not predefined like Home or Mobile)
4. Non favorite contacts will show like +123456 - custom name when there are no spaces  or chunking - even after country code.
5. I saved in phone storage

## With country code
1. but there is space after country code - ContactName - numberType
2. but there is no Space  anywhere  - Contact Name

## With no country code 

_when there is no country code and there is_ space - Only first word of contactName is shown
_when there is no country code and there is_ no space - `ContactName - ContactType`

*ContactName is only in `First Name`
*I have a number in ConTactName
Both no. are saved in 1 contact
ContactType is `Mobile`

### Additional information
This wasn't a problem in simple-phone-pro
`-` are no problem

### Expected behavior
Show the contact name from saved contacts

### Actual behavior
Shows number without spaces

**Comment by Aga-C** [comment]
What app are you using as Contacts app? Fossify Contacts, Simple Contacts or some other app?

**Comment by Rexadev** [comment]
> Fossify Contacts

@Aga-C Fossify Contacts!

**Comment by Aga-C** [comment]
Ok, so I tested the following cases and couldn't reproduce the problem:
1. Created a normal contact without spaces in number. Called it, then I've changed number to have spaces and I still see the contact in call log the same as it was. After calling, it again also it displays correctly.
2. Created a private contact without spaces in number. Called it, then I've changed number to have spaces and I still see the contact in call log the same as it was. After calling, it again also it displays correctly.
3. Called an unknown number. Then I created a contact from this number, but adding spaces in between. Now in call log I see the contact name, as it should be.

If you do it differently, please update reproduction steps and I will reopen the issue if the problem exists.

**Comment by Rexadev** [comment]
What is private contact ?

**Comment by Aga-C** [comment]
In Fossify/Simple Contacts you can save contacts in a private storage (not visible by other apps).

**Comment by Rexadev** [comment]
1. Try to save many (3) numbers in 1 contact.
2. Set one as favorite (I did the bottom one)
3. Name them custom (not predefined like Home or Mobile)
4. Non favorite contacts will show like `+123456 - custom name` when there are no spaces ` `or chunking `-` even after country code.
5. I saved in phone storage

@Aga-C

**Comment by Aga-C** [comment]
> Non favorite contacts will show like +123456 - custom name when there are no spaces  or chunking - even after country code.

Where it shows? I don't see it in call log.

**Comment by Aga-C** [comment]
I did exactly as you wrote in these steps. Call log doesn't show what number I used for the contact when I used a custom name. 

Also, nothing related to showing contacts has been made since the last version of Simple Dialer, so I can't tell what exactly can cause this problem on your side. Maybe someone else can reproduce it.

**Comment by Rexadev** [comment]
Also 

when there is no country code and there is space - Only first word of contactName is shown
when there is no country code and there is no space - `ContactName - ContactType`

*ContactName is only in `First Name`
*I have a number in ConTactName

@Aga-C

**Comment by Aga-C** [comment]
ContactType is custom, right? Not any predefined one like Work, Home, etc.?

**Comment by Rexadev** [comment]
> ContactType is custom, right? Not any predefined one like Work, Home, etc.?

In the contion where `Also when there is no country code` it's `Mobile`

**Comment by Rexadev** [comment]
@Aga-C updated `Also when there is no country code`

**Comment by Rexadev** [comment]
### Related bug
Editing 1 contact's no.'s formatting changes how another contact's number appears (i.e, if it shows No. or contact name), note both contacts have a common number but that is not in call logs

@Aga-C
