### ISSUE TITLE
[Duplicate]Incoming call add option to send pre saved SMS 

### ISSUE THREAD

**Issue by Rexadev** [FossifyOrg/Phone#64]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

1. Someone is calling I don't want to attend.
2. I can message and reject the call pre saved messages.
3. Messages like. 
Busy - Call you later
Driving - Call you Later
Call again if emergency.
In a Class.

### Why do you want this feature?

It would be nice

**Comment by Aga-C** [comment]
Can you add your thoughts to the already existing similar request: https://github.com/FossifyOrg/Phone/issues/4? Thanks!
