### ISSUE TITLE
a tab for groups

### ISSUE THREAD

**Issue by DoctorSubtilis** [FossifyOrg/Phone#75]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

As in (Fossify) ContactsY think that in Phone (Fossify app) it would be very importa to have not only (all) contacts and favorites, but also groups.
In **Contacts** they are correctly displayed and managed, therefore I think that it would be very easy to do the same in **Phone**.
Thank you!

### Why do you want this feature?

To find easy the contact I'm searching.

### Additional information

In True Phone the are groups, i.g..

**Comment by Aga-C** [comment]
We can't move each functionality from Contacts to Phone. As we have two separate apps, we need to keep some things out of the Phone, like groups. Now you can use groups in Contacts and just call someone from them here.

If you'd like to have both apps merged, please write your opinion here: https://github.com/FossifyOrg/Phone/discussions/13.

**Comment by DoctorSubtilis** [comment]
> We can't move each functionality from Contacts to Phone. As we have two separate apps, we need to keep some things out of the Phone, like groups. Now you can use groups in Contacts and just call someone from them here.
> 
> If you'd like to have both apps merged, please write your opinion here: #13.

Done!
But I still don't understand why only _this_ (not “each”) feature couldn't be present in Phone. Otherwise I have to switch from an app to the other: not exactly comfortable :).  
Unless you merge the two apps. But I'm not sure that it would be the best solution.

**Comment by igogo2** [comment]
The same opinion. It will be very convenient to have a Groups tab in Phone app.
As example LG phone have it.
