### ISSUE TITLE
bring apps on f droid and google play

### ISSUE THREAD

**Issue by Julian-1-2-3-4-5** [FossifyOrg/Phone#8]
**Checklist**
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
releasing apk's and uploading them to fdroid or hosting an own f droid repo with them

**Describe alternatives you've considered**
at least releasing them here on releases so one can update them via obtanium

**Comment by Aga-C** [comment]
Apps are being gradually released on GitHub and F-Droid. Currently, there are Gallery and Calendar, but the rest will also be released.

About Google Play: https://github.com/orgs/FossifyOrg/discussions/57.
