### ISSUE TITLE
Color icons for missed, received, outgoing calls in Call History tab

### ISSUE THREAD

**Issue by ksz16** [FossifyOrg/Phone#81]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

The date next to the icon for missed calls is currently red, making it poorly visible on dark themes. It would be better if the dates were always displayed in white (or black for light themes) and the icons were colored: red for missed calls (which is how it is now), green for outgoing calls and blue for incoming calls.

### Why do you want this feature?

Adding colored icons would improve visibility.

### Additional information

I noticed in closed issues that someone demanded an update of the icons (this was marked as wontfix). In my opinion, the current icons are fine. But it would be nice if they were colored.

**Comment by bb1a2** [comment]
And make the arrows a bit bigger, please.

**Comment by th23x** [comment]
I would even vote again for using a bit more prominent icons...it's really hard to distinguish in-coming vs out-going calls!

**Comment by naveensingh** [comment]
> I would even vote again for using a bit more prominent icons...it's really hard to distinguish in-coming vs out-going calls!

Since we have a limited screen real state, we'll go with 'pure' arrows. Just like in [Google Phone](https://fonts.google.com/icons?selected=Material+Symbols+Rounded:call_received:FILL@1;wght@500;GRAD@0;opsz@24&icon.query=call+rece&icon.style=Rounded).

> The date next to the icon for missed calls is currently red, making it poorly visible on dark themes

I would still color the text but adjust it for a proper contrast ratio. I bet some people (looking at me) just rely on the text color rather than the icon.

**Comment by naveensingh** [comment]
Sounds tempting on paper but this just increases visual clutter (with or without colored text) and makes it harder to distinguish between incoming/outgoing/missed calls. I'm just going to replace the existing icons with arrows and adjust the missed call color for better visibility.

**Comment by naveensingh** [comment]
It'll be available in the next update.
