### ISSUE TITLE
 Auto dismiss the missed call notification if the user opens the call log

### ISSUE THREAD

**Issue by bb1a2** [FossifyOrg/Phone#88]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

 Auto dismiss the missed call notification if the user opens the call log

### Why do you want this feature?

I am at the required screen already

**Comment by naveensingh** [comment]
Should be fixed in the next update.

**Comment by antodc** [comment]
@naveensingh Not sure whether it is intended or not, but in version 1.2.0 if you open the app and you are already in the call log, the missed call notification does not disappear. You have to select another tab and then go back to the logs.

**Comment by naveensingh** [comment]
@antodc thanks for reporting, I'll take a look at it.
