### ISSUE TITLE
 Keep "Hang Up" button on dialer

### ISSUE THREAD

**Issue by minosimo** [FossifyOrg/Phone#9]
**Checklist**
 - [X] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [X]  I have read the FAQ and my problem isn't listed.
 - [X]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [X]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

I opened this same issue in the original repo before reading about the sale.

I recently installed Dialer on my grandmother's phone. Her one frustration occurs when trying to hang up a call after using the dial pad. She checks her voicemail by calling a number, and needs to open the dial pad to interact with the voicemail. When done, she looks on screen but does not see the hang up button, and does not know where to find it, which means she goes back to the home screen and gets stuck with a call running in the background.

I compared to the stock Graphene OS dialer, which maintains the hang up button in the dialpad. I believe the Google dialer must do this as well.

I am guessing that Simple Dialer hides the call button to keep compatibility with smaller screens, and to make it easier to dial with one hand. That said, would there be interest in a PR that addresses this?

I see two potential methods, either an adaptive behavior where the dialpad hides or shows the hang up button depending on screen size, or a toggle in options for "Show hang-up button on dialpad". If a PR would be welcome, which would be better?

<img src="https://github.com/FossifyOrg/Dialer/assets/19229302/0f005542-30ca-4197-be9e-0762c9d76b5a" width="200" />

<img src="https://github.com/FossifyOrg/Dialer/assets/19229302/17745ce9-8ae4-473d-ada3-dc10db6482c8" width="200" />

**Comment by Aga-C** [comment]
> I am guessing that Simple Dialer hides the call button to keep compatibility with smaller screens, and to make it easier to dial with one hand. 

Even on large screens it works like this. Dialpad never had it implemented.

Also, I don't think the toggle in options is needed, I'd just always display the hang up button under the dialpad.

**Comment by naveensingh** [comment]
> I don't think the toggle in options is needed, I'd just always display the hang up button under the dialpad

@Aga-C I agree. The current dialpad UI isn't large enough to justify a dynamic behavior. 

> I am guessing that Simple Dialer hides the call button to keep compatibility with smaller screens

Not related to the dialpad but the overall button sizes were reduced to avoid overlapping elements on small screens.

> If a PR would be welcome, which would be better?

@minosimo Absolutely, PRs are welcome as long as they properly solve a problem and are not low quality. I suggest you wait for the initial release to avoid potential conflicts.
