### ISSUE TITLE
 Update name in call log if contact name (in Contacts app) is updated

### ISSUE THREAD

**Issue by bb1a2** [FossifyOrg/Phone#92]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I tried it.

Steps to reproduce:

- open Dialer, note any contact name.
- open Contacts, edit that contact name.
- open Dialer.
- close Dialer (swipe up in recents) and reopen.

Expected behavior:
- name is updated in Dialer.

Actual behavior:
- old name remains.

### Why do you want this feature?

-

**Comment by Aga-C** [comment]
It's a bug, so please create a new bug report with a properly filled form.

**Comment by bb1a2** [comment]
I wasn't sure, sorry.
