### ISSUE TITLE
[Feature request] Convert Call to text with FUTO voice imput

### ISSUE THREAD

**Issue by hetszunyukapanyanyimonyok** [FossifyOrg/Phone#95]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

It is basically a Google Pixels feature to recieve calls and convert them to text on the fly.
/if you dont have time or don't want to speak to that person/.

### Why do you want this feature?

I recieve more and more scam calls and I have to pickup almost everything.
This would help a lot knowing in text and filter unwanted unknown callers.
Or when I am on a meeting this solves the problem.

### Additional information

The FUTO Louis Rossmann's project and it works quite well .(my experience)
https://gitlab.futo.org/alex/voiceinput

**Comment by Aga-C** [comment]
How would this feature help you filter unwanted calls? You can block numbers, or you can use additional spam-filter apps like Yet Another Call Blocker. If there would be speech-to-text, you'd have to pick calls anyway.

**Comment by hetszunyukapanyanyimonyok** [comment]
@Aga-C thanks ! 
I checked Yet Another Call Blocker it is quite nice but not the same.
Every new number or unknown one could get this treatment.
(Spammers getting new numbers ever day an outdated database would not help as much.)
It would save a ton of time every day.
Spammers as they hear this function they drop the call, don't bother most of the time to cooperate.
And if it is friend or work you can see the text and just pickup or call back.
If I block ever new number I will not know who was that.
On the whole it would be a huge time saver.

**Comment by Aga-C** [comment]
Thanks for posting this feature request, but we have no plans of adding it for this use case. 

I understand that spam calls may be irritating, but I don't think it justifies adding nearly 70 MB to the app size just for that use case. Blocking spams should be automatic, yet how you describe it, you still need to pick up the call manually - the only difference is you don't bring the speaker to your ear, just read what someone's talking to you. Also, these bases, like in Yet Another Call Blocker, are regularly updated and from my experience there are rarely calls that aren't covered by it.
