### ISSUE TITLE
Show call time in call log

### ISSUE THREAD

**Issue by vertigo220** [FossifyOrg/Phone#96]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Despite there being a "Change date *and time* format" in settings, it only shows the date of calls. I'd like to be able to have it show the time as well as the date and duration.

### Why do you want this feature?

I often find it helpful when looking for an entry to see the time, since I may know roughly the time of day of the call.

### Additional information

Technically this could (should?) be another request, but it's tied to this: in order to provide the room for this, there should be a date option to display shortened months, e.g. Feb instead of February.

**Comment by tiredtiger** [comment]
I find it **very** helpful too (date+time of the call; note: same display format of the details view)
Maybe there could be an option to group the call of each day inserting a heading with the date (to save space for the time)

**Comment by mezhgano** [comment]
Enhancement? 
It should be by default, i think that's exactly what many people looking for.
Right now call history shows only time for today calls and show only date for calls older than today.
For me this leads to visual confusion between `:` and `.` in call history, so it will be nice to consistently show date and time in same format everywhere.

**Comment by naveensingh** [comment]
It'll be available in the next update.
