### ISSUE TITLE
Searching call log/history doesn't find numbers far back unless scrolling to them first

### ISSUE THREAD

**Issue by vertigo220** [FossifyOrg/Phone#97]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 13

### Affected device model

Samsung A71 5G UW

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Go to call history tab
2. Search for number from few/several months back
3. No results found
4. Scroll back until you've scrolled past the number
5. Retry the search
6. The number is now shown in the results

### Expected behavior

It should search _all_ numbers in the call log

### Actual behavior

It appears to only search a certain amount of time or a certain number of calls back and doesn't see numbers further back until seen by scrolling past them.

### Additional information

This may be related to #18, though in this case it doesn't matter how slowly I type it or if I give it plenty of time, the number(s) never show up until I've scrolled back to where they are in the history.

**Comment by naveensingh** [comment]
Should be fixed in the next update.
