### ISSUE TITLE
Searching call log/history then switching out of the app and back results in the search terms still being present but showing all history

### ISSUE THREAD

**Issue by vertigo220** [FossifyOrg/Phone#98]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 13

### Affected device model

Samsung A71 5G UW

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Go to Call History tab
2. Perform a search
3. Switch out of the app (to another or to home screen)
4. Switch back to the app
5. For a second or two, the search results still show, then it switches back to showing all history items (all calls)

### Expected behavior

It should _either_ clear the search or, ideally, maintain the search results

### Actual behavior

See above

**Comment by naveensingh** [comment]
Should be fixed in the next update.
